# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_xgui', [dirname(__file__)])
        except ImportError:
            import _xgui
            return _xgui
        if fp is not None:
            try:
                _mod = imp.load_module('_xgui', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _xgui = swig_import_helper()
    del swig_import_helper
else:
    import _xgui
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _xgui.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _xgui.SwigPyIterator_value(self)
    def incr(self, n=1): return _xgui.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _xgui.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _xgui.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _xgui.SwigPyIterator_equal(self, *args)
    def copy(self): return _xgui.SwigPyIterator_copy(self)
    def next(self): return _xgui.SwigPyIterator_next(self)
    def __next__(self): return _xgui.SwigPyIterator___next__(self)
    def previous(self): return _xgui.SwigPyIterator_previous(self)
    def advance(self, *args): return _xgui.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _xgui.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _xgui.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _xgui.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _xgui.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _xgui.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _xgui.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _xgui.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

keyShiftMask = _xgui.keyShiftMask
keyControlMask = _xgui.keyControlMask
keyAltMask = _xgui.keyAltMask
mouseLeftMask = _xgui.mouseLeftMask
mouseRightMask = _xgui.mouseRightMask
mouseMiddleMask = _xgui.mouseMiddleMask
PROPERTY_NOT_FOUND = _xgui.PROPERTY_NOT_FOUND
PROPERTY_READ_ONLY = _xgui.PROPERTY_READ_ONLY
PROPERTY_READ_WRITE = _xgui.PROPERTY_READ_WRITE
class FileExtension(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FileExtension, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FileExtension, name)
    __repr__ = _swig_repr
    __swig_setmethods__["name"] = _xgui.FileExtension_name_set
    __swig_getmethods__["name"] = _xgui.FileExtension_name_get
    if _newclass:name = _swig_property(_xgui.FileExtension_name_get, _xgui.FileExtension_name_set)
    __swig_setmethods__["extension"] = _xgui.FileExtension_extension_set
    __swig_getmethods__["extension"] = _xgui.FileExtension_extension_get
    if _newclass:extension = _swig_property(_xgui.FileExtension_extension_get, _xgui.FileExtension_extension_set)
    def __init__(self, *args): 
        this = _xgui.new_FileExtension(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _xgui.delete_FileExtension
    __del__ = lambda self : None;
FileExtension_swigregister = _xgui.FileExtension_swigregister
FileExtension_swigregister(FileExtension)
cvar = _xgui.cvar
EVT_BLOCK = cvar.EVT_BLOCK
EVT_PROPAGATE = cvar.EVT_PROPAGATE

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _xgui.StringVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _xgui.StringVector___nonzero__(self)
    def __bool__(self): return _xgui.StringVector___bool__(self)
    def __len__(self): return _xgui.StringVector___len__(self)
    def pop(self): return _xgui.StringVector_pop(self)
    def __getslice__(self, *args): return _xgui.StringVector___getslice__(self, *args)
    def __setslice__(self, *args): return _xgui.StringVector___setslice__(self, *args)
    def __delslice__(self, *args): return _xgui.StringVector___delslice__(self, *args)
    def __delitem__(self, *args): return _xgui.StringVector___delitem__(self, *args)
    def __getitem__(self, *args): return _xgui.StringVector___getitem__(self, *args)
    def __setitem__(self, *args): return _xgui.StringVector___setitem__(self, *args)
    def append(self, *args): return _xgui.StringVector_append(self, *args)
    def empty(self): return _xgui.StringVector_empty(self)
    def size(self): return _xgui.StringVector_size(self)
    def clear(self): return _xgui.StringVector_clear(self)
    def swap(self, *args): return _xgui.StringVector_swap(self, *args)
    def get_allocator(self): return _xgui.StringVector_get_allocator(self)
    def begin(self): return _xgui.StringVector_begin(self)
    def end(self): return _xgui.StringVector_end(self)
    def rbegin(self): return _xgui.StringVector_rbegin(self)
    def rend(self): return _xgui.StringVector_rend(self)
    def pop_back(self): return _xgui.StringVector_pop_back(self)
    def erase(self, *args): return _xgui.StringVector_erase(self, *args)
    def __init__(self, *args): 
        this = _xgui.new_StringVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _xgui.StringVector_push_back(self, *args)
    def front(self): return _xgui.StringVector_front(self)
    def back(self): return _xgui.StringVector_back(self)
    def assign(self, *args): return _xgui.StringVector_assign(self, *args)
    def resize(self, *args): return _xgui.StringVector_resize(self, *args)
    def insert(self, *args): return _xgui.StringVector_insert(self, *args)
    def reserve(self, *args): return _xgui.StringVector_reserve(self, *args)
    def capacity(self): return _xgui.StringVector_capacity(self)
    __swig_destroy__ = _xgui.delete_StringVector
    __del__ = lambda self : None;
StringVector_swigregister = _xgui.StringVector_swigregister
StringVector_swigregister(StringVector)

class FileExtensionsVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FileExtensionsVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FileExtensionsVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _xgui.FileExtensionsVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _xgui.FileExtensionsVector___nonzero__(self)
    def __bool__(self): return _xgui.FileExtensionsVector___bool__(self)
    def __len__(self): return _xgui.FileExtensionsVector___len__(self)
    def pop(self): return _xgui.FileExtensionsVector_pop(self)
    def __getslice__(self, *args): return _xgui.FileExtensionsVector___getslice__(self, *args)
    def __setslice__(self, *args): return _xgui.FileExtensionsVector___setslice__(self, *args)
    def __delslice__(self, *args): return _xgui.FileExtensionsVector___delslice__(self, *args)
    def __delitem__(self, *args): return _xgui.FileExtensionsVector___delitem__(self, *args)
    def __getitem__(self, *args): return _xgui.FileExtensionsVector___getitem__(self, *args)
    def __setitem__(self, *args): return _xgui.FileExtensionsVector___setitem__(self, *args)
    def append(self, *args): return _xgui.FileExtensionsVector_append(self, *args)
    def empty(self): return _xgui.FileExtensionsVector_empty(self)
    def size(self): return _xgui.FileExtensionsVector_size(self)
    def clear(self): return _xgui.FileExtensionsVector_clear(self)
    def swap(self, *args): return _xgui.FileExtensionsVector_swap(self, *args)
    def get_allocator(self): return _xgui.FileExtensionsVector_get_allocator(self)
    def begin(self): return _xgui.FileExtensionsVector_begin(self)
    def end(self): return _xgui.FileExtensionsVector_end(self)
    def rbegin(self): return _xgui.FileExtensionsVector_rbegin(self)
    def rend(self): return _xgui.FileExtensionsVector_rend(self)
    def pop_back(self): return _xgui.FileExtensionsVector_pop_back(self)
    def erase(self, *args): return _xgui.FileExtensionsVector_erase(self, *args)
    def __init__(self, *args): 
        this = _xgui.new_FileExtensionsVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _xgui.FileExtensionsVector_push_back(self, *args)
    def front(self): return _xgui.FileExtensionsVector_front(self)
    def back(self): return _xgui.FileExtensionsVector_back(self)
    def assign(self, *args): return _xgui.FileExtensionsVector_assign(self, *args)
    def resize(self, *args): return _xgui.FileExtensionsVector_resize(self, *args)
    def insert(self, *args): return _xgui.FileExtensionsVector_insert(self, *args)
    def reserve(self, *args): return _xgui.FileExtensionsVector_reserve(self, *args)
    def capacity(self): return _xgui.FileExtensionsVector_capacity(self)
    __swig_destroy__ = _xgui.delete_FileExtensionsVector
    __del__ = lambda self : None;
FileExtensionsVector_swigregister = _xgui.FileExtensionsVector_swigregister
FileExtensionsVector_swigregister(FileExtensionsVector)

class ClassInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ClassInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ClassInfo, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _xgui.delete_ClassInfo
    __del__ = lambda self : None;
    def isInstanceable(self): return _xgui.ClassInfo_isInstanceable(self)
    def mustFinalize(self): return _xgui.ClassInfo_mustFinalize(self)
    def className(self): return _xgui.ClassInfo_className(self)
    def tag(self): return _xgui.ClassInfo_tag(self)
    def dtd(self): return _xgui.ClassInfo_dtd(self)
    def isContainer(self): return _xgui.ClassInfo_isContainer(self)
    def isWidget(self): return _xgui.ClassInfo_isWidget(self)
    def isModel(self): return _xgui.ClassInfo_isModel(self)
    def isStyleManager(self): return _xgui.ClassInfo_isStyleManager(self)
    def canContain(self, *args): return _xgui.ClassInfo_canContain(self, *args)
    def canBeContainedIn(self, *args): return _xgui.ClassInfo_canBeContainedIn(self, *args)
    def registerProperty(self, *args): return _xgui.ClassInfo_registerProperty(self, *args)
    def getPropertySetter(self, *args): return _xgui.ClassInfo_getPropertySetter(self, *args)
    def getPropertyGetter(self, *args): return _xgui.ClassInfo_getPropertyGetter(self, *args)
    def properties(self): return _xgui.ClassInfo_properties(self)
    def hasProperty(self, *args): return _xgui.ClassInfo_hasProperty(self, *args)
    def initProperties(self): return _xgui.ClassInfo_initProperties(self)
    def registerInitProperty(self, *args): return _xgui.ClassInfo_registerInitProperty(self, *args)
    def registerMethod(self, *args): return _xgui.ClassInfo_registerMethod(self, *args)
    def findMethod(self, *args): return _xgui.ClassInfo_findMethod(self, *args)
    def create(self, *args): return _xgui.ClassInfo_create(self, *args)
    def finalize(self, *args): return _xgui.ClassInfo_finalize(self, *args)
ClassInfo_swigregister = _xgui.ClassInfo_swigregister
ClassInfo_swigregister(ClassInfo)

class ObjectClass(ClassInfo):
    __swig_setmethods__ = {}
    for _s in [ClassInfo]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ObjectClass, name, value)
    __swig_getmethods__ = {}
    for _s in [ClassInfo]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ObjectClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_ObjectClass()
        try: self.this.append(this)
        except: self.this = this
    def create(self, *args): return _xgui.ObjectClass_create(self, *args)
    def finalize(self, *args): return _xgui.ObjectClass_finalize(self, *args)
    def canContain(self, *args): return _xgui.ObjectClass_canContain(self, *args)
    def canBeContainedIn(self, *args): return _xgui.ObjectClass_canBeContainedIn(self, *args)
    def isInstanceable(self): return _xgui.ObjectClass_isInstanceable(self)
    def mustFinalize(self): return _xgui.ObjectClass_mustFinalize(self)
    def className(self): return _xgui.ObjectClass_className(self)
    def isContainer(self): return _xgui.ObjectClass_isContainer(self)
    def isWidget(self): return _xgui.ObjectClass_isWidget(self)
    def isModel(self): return _xgui.ObjectClass_isModel(self)
    def isStyleManager(self): return _xgui.ObjectClass_isStyleManager(self)
    __swig_destroy__ = _xgui.delete_ObjectClass
    __del__ = lambda self : None;
ObjectClass_swigregister = _xgui.ObjectClass_swigregister
ObjectClass_swigregister(ObjectClass)

class Object(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Object, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Object, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def className(self): return _xgui.Object_className(self)
    def getClass(self): return _xgui.Object_getClass(self)
    def isIdentifiedAs(self, *args): return _xgui.Object_isIdentifiedAs(self, *args)
    def id(self): return _xgui.Object_id(self)
    def setId(self, *args): return _xgui.Object_setId(self, *args)
    def store(self, *args): return _xgui.Object_store(self, *args)
    def retrieve(self, *args): return _xgui.Object_retrieve(self, *args)
    def unstore(self, *args): return _xgui.Object_unstore(self, *args)
    def set(self, *args): return _xgui.Object_set(self, *args)
    def get(self, *args): return _xgui.Object_get(self, *args)
    def registerProperty(self, *args): return _xgui.Object_registerProperty(self, *args)
    def properties(self): return _xgui.Object_properties(self)
    def hasProperty(self, *args): return _xgui.Object_hasProperty(self, *args)
    __swig_getmethods__["Unpack"] = lambda x: _xgui.Object_Unpack
    if _newclass:Unpack = staticmethod(_xgui.Object_Unpack)
    def pack(self): return _xgui.Object_pack(self)
    def findMethod(self, *args): return _xgui.Object_findMethod(self, *args)
    def registerMethod(self, *args): return _xgui.Object_registerMethod(self, *args)
    def call(self, *args): return _xgui.Object_call(self, *args)
Object_swigregister = _xgui.Object_swigregister
Object_swigregister(Object)

def Object_Unpack(*args):
  return _xgui.Object_Unpack(*args)
Object_Unpack = _xgui.Object_Unpack

class WidgetClass(ObjectClass):
    __swig_setmethods__ = {}
    for _s in [ObjectClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, WidgetClass, name, value)
    __swig_getmethods__ = {}
    for _s in [ObjectClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, WidgetClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_WidgetClass()
        try: self.this.append(this)
        except: self.this = this
    def isWidget(self): return _xgui.WidgetClass_isWidget(self)
    def className(self): return _xgui.WidgetClass_className(self)
    def canContain(self, *args): return _xgui.WidgetClass_canContain(self, *args)
    def canBeContainedIn(self, *args): return _xgui.WidgetClass_canBeContainedIn(self, *args)
    __swig_destroy__ = _xgui.delete_WidgetClass
    __del__ = lambda self : None;
WidgetClass_swigregister = _xgui.WidgetClass_swigregister
WidgetClass_swigregister(WidgetClass)

class Widget(Object):
    __swig_setmethods__ = {}
    for _s in [Object]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Widget, name, value)
    __swig_getmethods__ = {}
    for _s in [Object]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Widget, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def getImpl(self): return _xgui.Widget_getImpl(self)
    def setAsFloating(self): return _xgui.Widget_setAsFloating(self)
    def getParent(self): return _xgui.Widget_getParent(self)
    def getContext(self): return _xgui.Widget_getContext(self)
    def getPath(self): return _xgui.Widget_getPath(self)
    def linkEvent(self, *args): return _xgui.Widget_linkEvent(self, *args)
    def getEvent(self, *args): return _xgui.Widget_getEvent(self, *args)
    def hasEvent(self, *args): return _xgui.Widget_hasEvent(self, *args)
    def recalcLayout(self): return _xgui.Widget_recalcLayout(self)
    def getMousePos(self): return _xgui.Widget_getMousePos(self)
    def redraw(self): return _xgui.Widget_redraw(self)
    def delPyOwner(self, *args): return _xgui.Widget_delPyOwner(self, *args)
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

Widget_swigregister = _xgui.Widget_swigregister
Widget_swigregister(Widget)

class ModelClass(ObjectClass):
    __swig_setmethods__ = {}
    for _s in [ObjectClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ModelClass, name, value)
    __swig_getmethods__ = {}
    for _s in [ObjectClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ModelClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_ModelClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.ModelClass_className(self)
    def isInstanceable(self): return _xgui.ModelClass_isInstanceable(self)
    def isModel(self): return _xgui.ModelClass_isModel(self)
    def mustFinalize(self): return _xgui.ModelClass_mustFinalize(self)
    def create(self, *args): return _xgui.ModelClass_create(self, *args)
    def finalize(self, *args): return _xgui.ModelClass_finalize(self, *args)
    def canContain(self, *args): return _xgui.ModelClass_canContain(self, *args)
    def canBeContainedIn(self, *args): return _xgui.ModelClass_canBeContainedIn(self, *args)
    __swig_destroy__ = _xgui.delete_ModelClass
    __del__ = lambda self : None;
ModelClass_swigregister = _xgui.ModelClass_swigregister
ModelClass_swigregister(ModelClass)

class Model(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Model, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Model, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def appendChild(self, *args): return _xgui.Model_appendChild(self, *args)
    def insertChild(self, *args): return _xgui.Model_insertChild(self, *args)
    def removeChild(self, *args): return _xgui.Model_removeChild(self, *args)
    def removeAllChildren(self): return _xgui.Model_removeAllChildren(self)
    def setChild(self, *args): return _xgui.Model_setChild(self, *args)
    def getChild(self, *args): return _xgui.Model_getChild(self, *args)
    def findByPath(self, *args): return _xgui.Model_findByPath(self, *args)
    def setFlag(self, *args): return _xgui.Model_setFlag(self, *args)
    def unsetFlag(self, *args): return _xgui.Model_unsetFlag(self, *args)
    def getFlagStatus(self, *args): return _xgui.Model_getFlagStatus(self, *args)
    def setStyle(self, *args): return _xgui.Model_setStyle(self, *args)
    def getStyle(self): return _xgui.Model_getStyle(self)
    def addString(self, *args): return _xgui.Model_addString(self, *args)
    def delString(self, *args): return _xgui.Model_delString(self, *args)
    def setString(self, *args): return _xgui.Model_setString(self, *args)
    def getString(self, *args): return _xgui.Model_getString(self, *args)
    def clearStrings(self): return _xgui.Model_clearStrings(self)
    def numberOfStrings(self): return _xgui.Model_numberOfStrings(self)
    def updateViews(self): return _xgui.Model_updateViews(self)
    def size(self): return _xgui.Model_size(self)
Model_swigregister = _xgui.Model_swigregister
Model_swigregister(Model)

class ContainerClass(WidgetClass):
    __swig_setmethods__ = {}
    for _s in [WidgetClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ContainerClass, name, value)
    __swig_getmethods__ = {}
    for _s in [WidgetClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ContainerClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_ContainerClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.ContainerClass_className(self)
    def isContainer(self): return _xgui.ContainerClass_isContainer(self)
    def canContain(self, *args): return _xgui.ContainerClass_canContain(self, *args)
    def canBeContainedIn(self, *args): return _xgui.ContainerClass_canBeContainedIn(self, *args)
    __swig_destroy__ = _xgui.delete_ContainerClass
    __del__ = lambda self : None;
ContainerClass_swigregister = _xgui.ContainerClass_swigregister
ContainerClass_swigregister(ContainerClass)

class Container(Widget):
    __swig_setmethods__ = {}
    for _s in [Widget]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Container, name, value)
    __swig_getmethods__ = {}
    for _s in [Widget]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Container, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def findChild(self, *args): return _xgui.Container_findChild(self, *args)
    def findDirectChild(self, *args): return _xgui.Container_findDirectChild(self, *args)
    def getChild(self, *args): return _xgui.Container_getChild(self, *args)
    def size(self): return _xgui.Container_size(self)
Container_swigregister = _xgui.Container_swigregister
Container_swigregister(Container)

class ViewClass(WidgetClass):
    __swig_setmethods__ = {}
    for _s in [WidgetClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ViewClass, name, value)
    __swig_getmethods__ = {}
    for _s in [WidgetClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ViewClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_ViewClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.ViewClass_className(self)
    __swig_destroy__ = _xgui.delete_ViewClass
    __del__ = lambda self : None;
ViewClass_swigregister = _xgui.ViewClass_swigregister
ViewClass_swigregister(ViewClass)

class View(Widget):
    __swig_setmethods__ = {}
    for _s in [Widget]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, View, name, value)
    __swig_getmethods__ = {}
    for _s in [Widget]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, View, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def setModel(self, *args): return _xgui.View_setModel(self, *args)
    def getModel(self): return _xgui.View_getModel(self)
    def refresh(self): return _xgui.View_refresh(self)
    def isSelected(self, *args): return _xgui.View_isSelected(self, *args)
    def select(self, *args): return _xgui.View_select(self, *args)
    def selectAll(self, *args): return _xgui.View_selectAll(self, *args)
View_swigregister = _xgui.View_swigregister
View_swigregister(View)

class ImageClass(ObjectClass):
    __swig_setmethods__ = {}
    for _s in [ObjectClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ImageClass, name, value)
    __swig_getmethods__ = {}
    for _s in [ObjectClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ImageClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_ImageClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.ImageClass_className(self)
    def isInstanceable(self): return _xgui.ImageClass_isInstanceable(self)
    def create(self, *args): return _xgui.ImageClass_create(self, *args)
    __swig_destroy__ = _xgui.delete_ImageClass
    __del__ = lambda self : None;
ImageClass_swigregister = _xgui.ImageClass_swigregister
ImageClass_swigregister(ImageClass)

class Image(Object):
    __swig_setmethods__ = {}
    for _s in [Object]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Image, name, value)
    __swig_getmethods__ = {}
    for _s in [Object]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Image, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def ref(self): return _xgui.Image_ref(self)
    def unref(self): return _xgui.Image_unref(self)
    def getPath(self): return _xgui.Image_getPath(self)
    def getWidth(self): return _xgui.Image_getWidth(self)
    def getHeight(self): return _xgui.Image_getHeight(self)
    def getImpl(self): return _xgui.Image_getImpl(self)
    def isValid(self): return _xgui.Image_isValid(self)
Image_swigregister = _xgui.Image_swigregister
Image_swigregister(Image)

class StyleManagerClass(ObjectClass):
    __swig_setmethods__ = {}
    for _s in [ObjectClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, StyleManagerClass, name, value)
    __swig_getmethods__ = {}
    for _s in [ObjectClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, StyleManagerClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_StyleManagerClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.StyleManagerClass_className(self)
    def isStyleManager(self): return _xgui.StyleManagerClass_isStyleManager(self)
    def isInstanceable(self): return _xgui.StyleManagerClass_isInstanceable(self)
    def create(self, *args): return _xgui.StyleManagerClass_create(self, *args)
    def canContain(self, *args): return _xgui.StyleManagerClass_canContain(self, *args)
    def canBeContainedIn(self, *args): return _xgui.StyleManagerClass_canBeContainedIn(self, *args)
    __swig_destroy__ = _xgui.delete_StyleManagerClass
    __del__ = lambda self : None;
StyleManagerClass_swigregister = _xgui.StyleManagerClass_swigregister
StyleManagerClass_swigregister(StyleManagerClass)

class StyleManager(Object):
    __swig_setmethods__ = {}
    for _s in [Object]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, StyleManager, name, value)
    __swig_getmethods__ = {}
    for _s in [Object]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, StyleManager, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    TxtItalic = _xgui.StyleManager_TxtItalic
    TxtBold = _xgui.StyleManager_TxtBold
    TxtUnderline = _xgui.StyleManager_TxtUnderline
    TxtStrikeOut = _xgui.StyleManager_TxtStrikeOut
    def getImpl(self): return _xgui.StyleManager_getImpl(self)
    def ref(self): return _xgui.StyleManager_ref(self)
    def unref(self): return _xgui.StyleManager_unref(self)
    def addStyle(self, *args): return _xgui.StyleManager_addStyle(self, *args)
    def delStyle(self, *args): return _xgui.StyleManager_delStyle(self, *args)
    def isTextBold(self, *args): return _xgui.StyleManager_isTextBold(self, *args)
    def isTextItalic(self, *args): return _xgui.StyleManager_isTextItalic(self, *args)
    def isTextUnderlined(self, *args): return _xgui.StyleManager_isTextUnderlined(self, *args)
    def isTextStriked(self, *args): return _xgui.StyleManager_isTextStriked(self, *args)
    def getIcon(self, *args): return _xgui.StyleManager_getIcon(self, *args)
    def getFgColor(self, *args): return _xgui.StyleManager_getFgColor(self, *args)
    def getBgColor(self, *args): return _xgui.StyleManager_getBgColor(self, *args)
    def parseColorString(self, *args): return _xgui.StyleManager_parseColorString(self, *args)
    def dump(self): return _xgui.StyleManager_dump(self)
StyleManager_swigregister = _xgui.StyleManager_swigregister
StyleManager_swigregister(StyleManager)

class ButtonClass(WidgetClass):
    __swig_setmethods__ = {}
    for _s in [WidgetClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ButtonClass, name, value)
    __swig_getmethods__ = {}
    for _s in [WidgetClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ButtonClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_ButtonClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.ButtonClass_className(self)
    def isInstanceable(self): return _xgui.ButtonClass_isInstanceable(self)
    def create(self, *args): return _xgui.ButtonClass_create(self, *args)
    __swig_destroy__ = _xgui.delete_ButtonClass
    __del__ = lambda self : None;
ButtonClass_swigregister = _xgui.ButtonClass_swigregister
ButtonClass_swigregister(ButtonClass)

class Button(Widget):
    __swig_setmethods__ = {}
    for _s in [Widget]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Button, name, value)
    __swig_getmethods__ = {}
    for _s in [Widget]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Button, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def setIcon(self, *args): return _xgui.Button_setIcon(self, *args)
    def getIcon(self): return _xgui.Button_getIcon(self)
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

Button_swigregister = _xgui.Button_swigregister
Button_swigregister(Button)

class WindowClass(ContainerClass):
    __swig_setmethods__ = {}
    for _s in [ContainerClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, WindowClass, name, value)
    __swig_getmethods__ = {}
    for _s in [ContainerClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, WindowClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_WindowClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.WindowClass_className(self)
    def isInstanceable(self): return _xgui.WindowClass_isInstanceable(self)
    def create(self, *args): return _xgui.WindowClass_create(self, *args)
    def canBeContainedIn(self, *args): return _xgui.WindowClass_canBeContainedIn(self, *args)
    __swig_destroy__ = _xgui.delete_WindowClass
    __del__ = lambda self : None;
WindowClass_swigregister = _xgui.WindowClass_swigregister
WindowClass_swigregister(WindowClass)

class Window(Container):
    __swig_setmethods__ = {}
    for _s in [Container]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Window, name, value)
    __swig_getmethods__ = {}
    for _s in [Container]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Window, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def show(self): return _xgui.Window_show(self)
    def isModal(self): return _xgui.Window_isModal(self)
    def modalReturn(self, *args): return _xgui.Window_modalReturn(self, *args)
    def getRootChild(self): return _xgui.Window_getRootChild(self)
    def getMenu(self): return _xgui.Window_getMenu(self)
    def maximize(self): return _xgui.Window_maximize(self)
    def minimize(self): return _xgui.Window_minimize(self)
    def restore(self): return _xgui.Window_restore(self)
    def setIcon(self, *args): return _xgui.Window_setIcon(self, *args)
    def getIcon(self): return _xgui.Window_getIcon(self)
    def modalRun(self): return _xgui.Window_modalRun(self)
    def __del__(self):
            if self.valid: self.delPyOwner(self)

Window_swigregister = _xgui.Window_swigregister
Window_swigregister(Window)

class LabelClass(WidgetClass):
    __swig_setmethods__ = {}
    for _s in [WidgetClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, LabelClass, name, value)
    __swig_getmethods__ = {}
    for _s in [WidgetClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, LabelClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_LabelClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.LabelClass_className(self)
    def isInstanceable(self): return _xgui.LabelClass_isInstanceable(self)
    def create(self, *args): return _xgui.LabelClass_create(self, *args)
    __swig_destroy__ = _xgui.delete_LabelClass
    __del__ = lambda self : None;
LabelClass_swigregister = _xgui.LabelClass_swigregister
LabelClass_swigregister(LabelClass)

class Label(Widget):
    __swig_setmethods__ = {}
    for _s in [Widget]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Label, name, value)
    __swig_getmethods__ = {}
    for _s in [Widget]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Label, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

Label_swigregister = _xgui.Label_swigregister
Label_swigregister(Label)

class HBoxClass(ContainerClass):
    __swig_setmethods__ = {}
    for _s in [ContainerClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, HBoxClass, name, value)
    __swig_getmethods__ = {}
    for _s in [ContainerClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, HBoxClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_HBoxClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.HBoxClass_className(self)
    def isInstanceable(self): return _xgui.HBoxClass_isInstanceable(self)
    def create(self, *args): return _xgui.HBoxClass_create(self, *args)
    def canContain(self, *args): return _xgui.HBoxClass_canContain(self, *args)
    __swig_destroy__ = _xgui.delete_HBoxClass
    __del__ = lambda self : None;
HBoxClass_swigregister = _xgui.HBoxClass_swigregister
HBoxClass_swigregister(HBoxClass)

class HBox(Container):
    __swig_setmethods__ = {}
    for _s in [Container]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, HBox, name, value)
    __swig_getmethods__ = {}
    for _s in [Container]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, HBox, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def setExpand(self, *args): return _xgui.HBox_setExpand(self, *args)
    def getExpand(self, *args): return _xgui.HBox_getExpand(self, *args)
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

HBox_swigregister = _xgui.HBox_swigregister
HBox_swigregister(HBox)

class VBoxClass(ContainerClass):
    __swig_setmethods__ = {}
    for _s in [ContainerClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, VBoxClass, name, value)
    __swig_getmethods__ = {}
    for _s in [ContainerClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, VBoxClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_VBoxClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.VBoxClass_className(self)
    def isInstanceable(self): return _xgui.VBoxClass_isInstanceable(self)
    def create(self, *args): return _xgui.VBoxClass_create(self, *args)
    def canContain(self, *args): return _xgui.VBoxClass_canContain(self, *args)
    __swig_destroy__ = _xgui.delete_VBoxClass
    __del__ = lambda self : None;
VBoxClass_swigregister = _xgui.VBoxClass_swigregister
VBoxClass_swigregister(VBoxClass)

class VBox(Container):
    __swig_setmethods__ = {}
    for _s in [Container]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, VBox, name, value)
    __swig_getmethods__ = {}
    for _s in [Container]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, VBox, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def setExpand(self, *args): return _xgui.VBox_setExpand(self, *args)
    def getExpand(self, *args): return _xgui.VBox_getExpand(self, *args)
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

VBox_swigregister = _xgui.VBox_swigregister
VBox_swigregister(VBox)

class EntryClass(WidgetClass):
    __swig_setmethods__ = {}
    for _s in [WidgetClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, EntryClass, name, value)
    __swig_getmethods__ = {}
    for _s in [WidgetClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, EntryClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_EntryClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.EntryClass_className(self)
    def isInstanceable(self): return _xgui.EntryClass_isInstanceable(self)
    def create(self, *args): return _xgui.EntryClass_create(self, *args)
    __swig_destroy__ = _xgui.delete_EntryClass
    __del__ = lambda self : None;
EntryClass_swigregister = _xgui.EntryClass_swigregister
EntryClass_swigregister(EntryClass)

class Entry(Widget):
    __swig_setmethods__ = {}
    for _s in [Widget]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Entry, name, value)
    __swig_getmethods__ = {}
    for _s in [Widget]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Entry, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def appendText(self, *args): return _xgui.Entry_appendText(self, *args)
    def prependText(self, *args): return _xgui.Entry_prependText(self, *args)
    def insertText(self, *args): return _xgui.Entry_insertText(self, *args)
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

Entry_swigregister = _xgui.Entry_swigregister
Entry_swigregister(Entry)

class ListClass(ViewClass):
    __swig_setmethods__ = {}
    for _s in [ViewClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ListClass, name, value)
    __swig_getmethods__ = {}
    for _s in [ViewClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ListClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_ListClass()
        try: self.this.append(this)
        except: self.this = this
    def isInstanceable(self): return _xgui.ListClass_isInstanceable(self)
    def className(self): return _xgui.ListClass_className(self)
    def create(self, *args): return _xgui.ListClass_create(self, *args)
    def canContain(self, *args): return _xgui.ListClass_canContain(self, *args)
    __swig_destroy__ = _xgui.delete_ListClass
    __del__ = lambda self : None;
ListClass_swigregister = _xgui.ListClass_swigregister
ListClass_swigregister(ListClass)

class List(View):
    __swig_setmethods__ = {}
    for _s in [View]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, List, name, value)
    __swig_getmethods__ = {}
    for _s in [View]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, List, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def addColumn(self, *args): return _xgui.List_addColumn(self, *args)
    def delColumn(self, *args): return _xgui.List_delColumn(self, *args)
    def sort(self, *args): return _xgui.List_sort(self, *args)
    def isChecked(self, *args): return _xgui.List_isChecked(self, *args)
    def check(self, *args): return _xgui.List_check(self, *args)
    def checkAll(self, *args): return _xgui.List_checkAll(self, *args)
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

List_swigregister = _xgui.List_swigregister
List_swigregister(List)

class TreeClass(ViewClass):
    __swig_setmethods__ = {}
    for _s in [ViewClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TreeClass, name, value)
    __swig_getmethods__ = {}
    for _s in [ViewClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TreeClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_TreeClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.TreeClass_className(self)
    def isInstanceable(self): return _xgui.TreeClass_isInstanceable(self)
    def create(self, *args): return _xgui.TreeClass_create(self, *args)
    def canContain(self, *args): return _xgui.TreeClass_canContain(self, *args)
    __swig_destroy__ = _xgui.delete_TreeClass
    __del__ = lambda self : None;
TreeClass_swigregister = _xgui.TreeClass_swigregister
TreeClass_swigregister(TreeClass)

class Tree(View):
    __swig_setmethods__ = {}
    for _s in [View]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Tree, name, value)
    __swig_getmethods__ = {}
    for _s in [View]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Tree, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def sort(self, *args): return _xgui.Tree_sort(self, *args)
    def expand(self, *args): return _xgui.Tree_expand(self, *args)
    def collapse(self, *args): return _xgui.Tree_collapse(self, *args)
    def isChecked(self, *args): return _xgui.Tree_isChecked(self, *args)
    def check(self, *args): return _xgui.Tree_check(self, *args)
    def checkAll(self, *args): return _xgui.Tree_checkAll(self, *args)
Tree_swigregister = _xgui.Tree_swigregister
Tree_swigregister(Tree)

class ToolbarClass(WidgetClass):
    __swig_setmethods__ = {}
    for _s in [WidgetClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ToolbarClass, name, value)
    __swig_getmethods__ = {}
    for _s in [WidgetClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ToolbarClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_ToolbarClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.ToolbarClass_className(self)
    def isInstanceable(self): return _xgui.ToolbarClass_isInstanceable(self)
    def create(self, *args): return _xgui.ToolbarClass_create(self, *args)
    def canContain(self, *args): return _xgui.ToolbarClass_canContain(self, *args)
    __swig_destroy__ = _xgui.delete_ToolbarClass
    __del__ = lambda self : None;
ToolbarClass_swigregister = _xgui.ToolbarClass_swigregister
ToolbarClass_swigregister(ToolbarClass)

class Toolbar(Widget):
    __swig_setmethods__ = {}
    for _s in [Widget]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Toolbar, name, value)
    __swig_getmethods__ = {}
    for _s in [Widget]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Toolbar, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def addItem(self, *args): return _xgui.Toolbar_addItem(self, *args)
    def delItem(self, *args): return _xgui.Toolbar_delItem(self, *args)
    def enableButton(self, *args): return _xgui.Toolbar_enableButton(self, *args)
    def disableButton(self, *args): return _xgui.Toolbar_disableButton(self, *args)
    def checkButton(self, *args): return _xgui.Toolbar_checkButton(self, *args)
    def uncheckButton(self, *args): return _xgui.Toolbar_uncheckButton(self, *args)
    def isButtonChecked(self, *args): return _xgui.Toolbar_isButtonChecked(self, *args)
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

Toolbar_swigregister = _xgui.Toolbar_swigregister
Toolbar_swigregister(Toolbar)

class ComboboxClass(ViewClass):
    __swig_setmethods__ = {}
    for _s in [ViewClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ComboboxClass, name, value)
    __swig_getmethods__ = {}
    for _s in [ViewClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ComboboxClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_ComboboxClass()
        try: self.this.append(this)
        except: self.this = this
    def isInstanceable(self): return _xgui.ComboboxClass_isInstanceable(self)
    def className(self): return _xgui.ComboboxClass_className(self)
    def create(self, *args): return _xgui.ComboboxClass_create(self, *args)
    def canContain(self, *args): return _xgui.ComboboxClass_canContain(self, *args)
    __swig_destroy__ = _xgui.delete_ComboboxClass
    __del__ = lambda self : None;
ComboboxClass_swigregister = _xgui.ComboboxClass_swigregister
ComboboxClass_swigregister(ComboboxClass)

class Combobox(View):
    __swig_setmethods__ = {}
    for _s in [View]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Combobox, name, value)
    __swig_getmethods__ = {}
    for _s in [View]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Combobox, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def insertText(self, *args): return _xgui.Combobox_insertText(self, *args)
    def appendText(self, *args): return _xgui.Combobox_appendText(self, *args)
    def prependText(self, *args): return _xgui.Combobox_prependText(self, *args)
    def popup(self): return _xgui.Combobox_popup(self)
    def popdown(self): return _xgui.Combobox_popdown(self)
    def isEditable(self): return _xgui.Combobox_isEditable(self)
    def setAsEditable(self, *args): return _xgui.Combobox_setAsEditable(self, *args)
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

Combobox_swigregister = _xgui.Combobox_swigregister
Combobox_swigregister(Combobox)

class SpaceClass(WidgetClass):
    __swig_setmethods__ = {}
    for _s in [WidgetClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SpaceClass, name, value)
    __swig_getmethods__ = {}
    for _s in [WidgetClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, SpaceClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_SpaceClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.SpaceClass_className(self)
    def isInstanceable(self): return _xgui.SpaceClass_isInstanceable(self)
    def create(self, *args): return _xgui.SpaceClass_create(self, *args)
    __swig_destroy__ = _xgui.delete_SpaceClass
    __del__ = lambda self : None;
SpaceClass_swigregister = _xgui.SpaceClass_swigregister
SpaceClass_swigregister(SpaceClass)

class Space(Widget):
    __swig_setmethods__ = {}
    for _s in [Widget]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Space, name, value)
    __swig_getmethods__ = {}
    for _s in [Widget]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Space, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

Space_swigregister = _xgui.Space_swigregister
Space_swigregister(Space)

class CheckboxClass(WidgetClass):
    __swig_setmethods__ = {}
    for _s in [WidgetClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CheckboxClass, name, value)
    __swig_getmethods__ = {}
    for _s in [WidgetClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, CheckboxClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_CheckboxClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.CheckboxClass_className(self)
    def isInstanceable(self): return _xgui.CheckboxClass_isInstanceable(self)
    def create(self, *args): return _xgui.CheckboxClass_create(self, *args)
    __swig_destroy__ = _xgui.delete_CheckboxClass
    __del__ = lambda self : None;
CheckboxClass_swigregister = _xgui.CheckboxClass_swigregister
CheckboxClass_swigregister(CheckboxClass)

class Checkbox(Widget):
    __swig_setmethods__ = {}
    for _s in [Widget]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Checkbox, name, value)
    __swig_getmethods__ = {}
    for _s in [Widget]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Checkbox, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def getValue(self): return _xgui.Checkbox_getValue(self)
    def setValue(self, *args): return _xgui.Checkbox_setValue(self, *args)
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

Checkbox_swigregister = _xgui.Checkbox_swigregister
Checkbox_swigregister(Checkbox)

class ProgressbarClass(WidgetClass):
    __swig_setmethods__ = {}
    for _s in [WidgetClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ProgressbarClass, name, value)
    __swig_getmethods__ = {}
    for _s in [WidgetClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ProgressbarClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_ProgressbarClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.ProgressbarClass_className(self)
    def isInstanceable(self): return _xgui.ProgressbarClass_isInstanceable(self)
    def create(self, *args): return _xgui.ProgressbarClass_create(self, *args)
    __swig_destroy__ = _xgui.delete_ProgressbarClass
    __del__ = lambda self : None;
ProgressbarClass_swigregister = _xgui.ProgressbarClass_swigregister
ProgressbarClass_swigregister(ProgressbarClass)

class Progressbar(Widget):
    __swig_setmethods__ = {}
    for _s in [Widget]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Progressbar, name, value)
    __swig_getmethods__ = {}
    for _s in [Widget]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Progressbar, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def getPos(self): return _xgui.Progressbar_getPos(self)
    def setPos(self, *args): return _xgui.Progressbar_setPos(self, *args)
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

Progressbar_swigregister = _xgui.Progressbar_swigregister
Progressbar_swigregister(Progressbar)

class SliderClass(WidgetClass):
    __swig_setmethods__ = {}
    for _s in [WidgetClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SliderClass, name, value)
    __swig_getmethods__ = {}
    for _s in [WidgetClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, SliderClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_SliderClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.SliderClass_className(self)
    def isInstanceable(self): return _xgui.SliderClass_isInstanceable(self)
    def create(self, *args): return _xgui.SliderClass_create(self, *args)
    __swig_destroy__ = _xgui.delete_SliderClass
    __del__ = lambda self : None;
SliderClass_swigregister = _xgui.SliderClass_swigregister
SliderClass_swigregister(SliderClass)

class Slider(Widget):
    __swig_setmethods__ = {}
    for _s in [Widget]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Slider, name, value)
    __swig_getmethods__ = {}
    for _s in [Widget]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Slider, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def getPos(self): return _xgui.Slider_getPos(self)
    def setPos(self, *args): return _xgui.Slider_setPos(self, *args)
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

Slider_swigregister = _xgui.Slider_swigregister
Slider_swigregister(Slider)

class MenuClass(WidgetClass):
    __swig_setmethods__ = {}
    for _s in [WidgetClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, MenuClass, name, value)
    __swig_getmethods__ = {}
    for _s in [WidgetClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, MenuClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_MenuClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.MenuClass_className(self)
    def isInstanceable(self): return _xgui.MenuClass_isInstanceable(self)
    def create(self, *args): return _xgui.MenuClass_create(self, *args)
    def canContain(self, *args): return _xgui.MenuClass_canContain(self, *args)
    def canBeContainedIn(self, *args): return _xgui.MenuClass_canBeContainedIn(self, *args)
    __swig_destroy__ = _xgui.delete_MenuClass
    __del__ = lambda self : None;
MenuClass_swigregister = _xgui.MenuClass_swigregister
MenuClass_swigregister(MenuClass)

class Menu(Widget):
    __swig_setmethods__ = {}
    for _s in [Widget]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Menu, name, value)
    __swig_getmethods__ = {}
    for _s in [Widget]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Menu, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def addItem(self, *args): return _xgui.Menu_addItem(self, *args)
    def delItem(self, *args): return _xgui.Menu_delItem(self, *args)
    def popupMenu(self, *args): return _xgui.Menu_popupMenu(self, *args)
    def enableItem(self, *args): return _xgui.Menu_enableItem(self, *args)
    def disableItem(self, *args): return _xgui.Menu_disableItem(self, *args)
    def isItemEnabled(self, *args): return _xgui.Menu_isItemEnabled(self, *args)
    def checkItem(self, *args): return _xgui.Menu_checkItem(self, *args)
    def uncheckItem(self, *args): return _xgui.Menu_uncheckItem(self, *args)
    def isItemChecked(self, *args): return _xgui.Menu_isItemChecked(self, *args)
    def setItemText(self, *args): return _xgui.Menu_setItemText(self, *args)
    def getItemText(self, *args): return _xgui.Menu_getItemText(self, *args)
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

Menu_swigregister = _xgui.Menu_swigregister
Menu_swigregister(Menu)

class TabClass(ContainerClass):
    __swig_setmethods__ = {}
    for _s in [ContainerClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TabClass, name, value)
    __swig_getmethods__ = {}
    for _s in [ContainerClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TabClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_TabClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.TabClass_className(self)
    def isInstanceable(self): return _xgui.TabClass_isInstanceable(self)
    def create(self, *args): return _xgui.TabClass_create(self, *args)
    def canContain(self, *args): return _xgui.TabClass_canContain(self, *args)
    __swig_destroy__ = _xgui.delete_TabClass
    __del__ = lambda self : None;
TabClass_swigregister = _xgui.TabClass_swigregister
TabClass_swigregister(TabClass)

class Tab(Container):
    __swig_setmethods__ = {}
    for _s in [Container]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Tab, name, value)
    __swig_getmethods__ = {}
    for _s in [Container]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Tab, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def setPageIcon(self, *args): return _xgui.Tab_setPageIcon(self, *args)
    def setPageLabel(self, *args): return _xgui.Tab_setPageLabel(self, *args)
    def getPageIcon(self, *args): return _xgui.Tab_getPageIcon(self, *args)
    def getPageLabel(self, *args): return _xgui.Tab_getPageLabel(self, *args)
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

Tab_swigregister = _xgui.Tab_swigregister
Tab_swigregister(Tab)

class SpinClass(WidgetClass):
    __swig_setmethods__ = {}
    for _s in [WidgetClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SpinClass, name, value)
    __swig_getmethods__ = {}
    for _s in [WidgetClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, SpinClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_SpinClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.SpinClass_className(self)
    def isInstanceable(self): return _xgui.SpinClass_isInstanceable(self)
    def create(self, *args): return _xgui.SpinClass_create(self, *args)
    __swig_destroy__ = _xgui.delete_SpinClass
    __del__ = lambda self : None;
SpinClass_swigregister = _xgui.SpinClass_swigregister
SpinClass_swigregister(SpinClass)

class Spin(Widget):
    __swig_setmethods__ = {}
    for _s in [Widget]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Spin, name, value)
    __swig_getmethods__ = {}
    for _s in [Widget]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Spin, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

Spin_swigregister = _xgui.Spin_swigregister
Spin_swigregister(Spin)

class ImageViewClass(WidgetClass):
    __swig_setmethods__ = {}
    for _s in [WidgetClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ImageViewClass, name, value)
    __swig_getmethods__ = {}
    for _s in [WidgetClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ImageViewClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_ImageViewClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.ImageViewClass_className(self)
    def isInstanceable(self): return _xgui.ImageViewClass_isInstanceable(self)
    def create(self, *args): return _xgui.ImageViewClass_create(self, *args)
    __swig_destroy__ = _xgui.delete_ImageViewClass
    __del__ = lambda self : None;
ImageViewClass_swigregister = _xgui.ImageViewClass_swigregister
ImageViewClass_swigregister(ImageViewClass)

class ImageView(Widget):
    __swig_setmethods__ = {}
    for _s in [Widget]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ImageView, name, value)
    __swig_getmethods__ = {}
    for _s in [Widget]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ImageView, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def getImage(self): return _xgui.ImageView_getImage(self)
    def setImage(self, *args): return _xgui.ImageView_setImage(self, *args)
    def getViewSize(self): return _xgui.ImageView_getViewSize(self)
    def isScrolled(self): return _xgui.ImageView_isScrolled(self)
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

ImageView_swigregister = _xgui.ImageView_swigregister
ImageView_swigregister(ImageView)

class FrameClass(ContainerClass):
    __swig_setmethods__ = {}
    for _s in [ContainerClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, FrameClass, name, value)
    __swig_getmethods__ = {}
    for _s in [ContainerClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, FrameClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_FrameClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.FrameClass_className(self)
    def isInstanceable(self): return _xgui.FrameClass_isInstanceable(self)
    def create(self, *args): return _xgui.FrameClass_create(self, *args)
    __swig_destroy__ = _xgui.delete_FrameClass
    __del__ = lambda self : None;
FrameClass_swigregister = _xgui.FrameClass_swigregister
FrameClass_swigregister(FrameClass)

class Frame(Container):
    __swig_setmethods__ = {}
    for _s in [Container]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Frame, name, value)
    __swig_getmethods__ = {}
    for _s in [Container]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Frame, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def getRootChild(self): return _xgui.Frame_getRootChild(self)
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

Frame_swigregister = _xgui.Frame_swigregister
Frame_swigregister(Frame)

class CalendarClass(WidgetClass):
    __swig_setmethods__ = {}
    for _s in [WidgetClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CalendarClass, name, value)
    __swig_getmethods__ = {}
    for _s in [WidgetClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, CalendarClass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xgui.new_CalendarClass()
        try: self.this.append(this)
        except: self.this = this
    def className(self): return _xgui.CalendarClass_className(self)
    def isInstanceable(self): return _xgui.CalendarClass_isInstanceable(self)
    def create(self, *args): return _xgui.CalendarClass_create(self, *args)
    __swig_destroy__ = _xgui.delete_CalendarClass
    __del__ = lambda self : None;
CalendarClass_swigregister = _xgui.CalendarClass_swigregister
CalendarClass_swigregister(CalendarClass)

class Calendar(Widget):
    __swig_setmethods__ = {}
    for _s in [Widget]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Calendar, name, value)
    __swig_getmethods__ = {}
    for _s in [Widget]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Calendar, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def __del__(self):
    	if self.valid: self.delPyOwner(self)

Calendar_swigregister = _xgui.Calendar_swigregister
Calendar_swigregister(Calendar)

class Master(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Master, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Master, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_getmethods__["Instance"] = lambda x: _xgui.Master_Instance
    if _newclass:Instance = staticmethod(_xgui.Master_Instance)
    __swig_getmethods__["Quit"] = lambda x: _xgui.Master_Quit
    if _newclass:Quit = staticmethod(_xgui.Master_Quit)
    __swig_getmethods__["RegisterIdleCallback"] = lambda x: _xgui.Master_RegisterIdleCallback
    if _newclass:RegisterIdleCallback = staticmethod(_xgui.Master_RegisterIdleCallback)
    __swig_getmethods__["InitDynamicClasses"] = lambda x: _xgui.Master_InitDynamicClasses
    if _newclass:InitDynamicClasses = staticmethod(_xgui.Master_InitDynamicClasses)
    __swig_getmethods__["CreateModel"] = lambda x: _xgui.Master_CreateModel
    if _newclass:CreateModel = staticmethod(_xgui.Master_CreateModel)
    __swig_getmethods__["DestroyModel"] = lambda x: _xgui.Master_DestroyModel
    if _newclass:DestroyModel = staticmethod(_xgui.Master_DestroyModel)
    __swig_getmethods__["CreateStyleManager"] = lambda x: _xgui.Master_CreateStyleManager
    if _newclass:CreateStyleManager = staticmethod(_xgui.Master_CreateStyleManager)
    __swig_getmethods__["DestroyStyleManager"] = lambda x: _xgui.Master_DestroyStyleManager
    if _newclass:DestroyStyleManager = staticmethod(_xgui.Master_DestroyStyleManager)
    __swig_getmethods__["LoadImage"] = lambda x: _xgui.Master_LoadImage
    if _newclass:LoadImage = staticmethod(_xgui.Master_LoadImage)
    __swig_getmethods__["GetImage"] = lambda x: _xgui.Master_GetImage
    if _newclass:GetImage = staticmethod(_xgui.Master_GetImage)
    __swig_getmethods__["NullImage"] = lambda x: _xgui.Master_NullImage
    if _newclass:NullImage = staticmethod(_xgui.Master_NullImage)
    __swig_getmethods__["FindContext"] = lambda x: _xgui.Master_FindContext
    if _newclass:FindContext = staticmethod(_xgui.Master_FindContext)
    __swig_getmethods__["CreateWindow"] = lambda x: _xgui.Master_CreateWindow
    if _newclass:CreateWindow = staticmethod(_xgui.Master_CreateWindow)
    __swig_getmethods__["CreateButton"] = lambda x: _xgui.Master_CreateButton
    if _newclass:CreateButton = staticmethod(_xgui.Master_CreateButton)
    __swig_getmethods__["CreateLabel"] = lambda x: _xgui.Master_CreateLabel
    if _newclass:CreateLabel = staticmethod(_xgui.Master_CreateLabel)
    __swig_getmethods__["CreateEntry"] = lambda x: _xgui.Master_CreateEntry
    if _newclass:CreateEntry = staticmethod(_xgui.Master_CreateEntry)
    __swig_getmethods__["CreateVBox"] = lambda x: _xgui.Master_CreateVBox
    if _newclass:CreateVBox = staticmethod(_xgui.Master_CreateVBox)
    __swig_getmethods__["CreateHBox"] = lambda x: _xgui.Master_CreateHBox
    if _newclass:CreateHBox = staticmethod(_xgui.Master_CreateHBox)
    __swig_getmethods__["CreateImageView"] = lambda x: _xgui.Master_CreateImageView
    if _newclass:CreateImageView = staticmethod(_xgui.Master_CreateImageView)
    __swig_getmethods__["CreateList"] = lambda x: _xgui.Master_CreateList
    if _newclass:CreateList = staticmethod(_xgui.Master_CreateList)
    __swig_getmethods__["CreateToolbar"] = lambda x: _xgui.Master_CreateToolbar
    if _newclass:CreateToolbar = staticmethod(_xgui.Master_CreateToolbar)
    __swig_getmethods__["CreateCombobox"] = lambda x: _xgui.Master_CreateCombobox
    if _newclass:CreateCombobox = staticmethod(_xgui.Master_CreateCombobox)
    __swig_getmethods__["CreateSpace"] = lambda x: _xgui.Master_CreateSpace
    if _newclass:CreateSpace = staticmethod(_xgui.Master_CreateSpace)
    __swig_getmethods__["CreateCheckbox"] = lambda x: _xgui.Master_CreateCheckbox
    if _newclass:CreateCheckbox = staticmethod(_xgui.Master_CreateCheckbox)
    __swig_getmethods__["CreateProgressbar"] = lambda x: _xgui.Master_CreateProgressbar
    if _newclass:CreateProgressbar = staticmethod(_xgui.Master_CreateProgressbar)
    __swig_getmethods__["CreateSlider"] = lambda x: _xgui.Master_CreateSlider
    if _newclass:CreateSlider = staticmethod(_xgui.Master_CreateSlider)
    __swig_getmethods__["CreateMenu"] = lambda x: _xgui.Master_CreateMenu
    if _newclass:CreateMenu = staticmethod(_xgui.Master_CreateMenu)
    __swig_getmethods__["CreateTab"] = lambda x: _xgui.Master_CreateTab
    if _newclass:CreateTab = staticmethod(_xgui.Master_CreateTab)
    __swig_getmethods__["CreateSpin"] = lambda x: _xgui.Master_CreateSpin
    if _newclass:CreateSpin = staticmethod(_xgui.Master_CreateSpin)
    __swig_getmethods__["CreateFrame"] = lambda x: _xgui.Master_CreateFrame
    if _newclass:CreateFrame = staticmethod(_xgui.Master_CreateFrame)
    __swig_getmethods__["CreateCalendar"] = lambda x: _xgui.Master_CreateCalendar
    if _newclass:CreateCalendar = staticmethod(_xgui.Master_CreateCalendar)
    __swig_getmethods__["CreateTree"] = lambda x: _xgui.Master_CreateTree
    if _newclass:CreateTree = staticmethod(_xgui.Master_CreateTree)
    __swig_getmethods__["LoadXml"] = lambda x: _xgui.Master_LoadXml
    if _newclass:LoadXml = staticmethod(_xgui.Master_LoadXml)
    __swig_getmethods__["DestroyWidget"] = lambda x: _xgui.Master_DestroyWidget
    if _newclass:DestroyWidget = staticmethod(_xgui.Master_DestroyWidget)
    __swig_getmethods__["InitThreads"] = lambda x: _xgui.Master_InitThreads
    if _newclass:InitThreads = staticmethod(_xgui.Master_InitThreads)
    __swig_getmethods__["QuitThreads"] = lambda x: _xgui.Master_QuitThreads
    if _newclass:QuitThreads = staticmethod(_xgui.Master_QuitThreads)
    __swig_getmethods__["GuiLock"] = lambda x: _xgui.Master_GuiLock
    if _newclass:GuiLock = staticmethod(_xgui.Master_GuiLock)
    __swig_getmethods__["GuiUnlock"] = lambda x: _xgui.Master_GuiUnlock
    if _newclass:GuiUnlock = staticmethod(_xgui.Master_GuiUnlock)
    __swig_getmethods__["Run"] = lambda x: _xgui.Master_Run
    if _newclass:Run = staticmethod(_xgui.Master_Run)
    __swig_getmethods__["OpenFileDialog"] = lambda x: _xgui.Master_OpenFileDialog
    if _newclass:OpenFileDialog = staticmethod(_xgui.Master_OpenFileDialog)
    __swig_getmethods__["SaveFileDialog"] = lambda x: _xgui.Master_SaveFileDialog
    if _newclass:SaveFileDialog = staticmethod(_xgui.Master_SaveFileDialog)
    __swig_getmethods__["MessageDialog"] = lambda x: _xgui.Master_MessageDialog
    if _newclass:MessageDialog = staticmethod(_xgui.Master_MessageDialog)
Master_swigregister = _xgui.Master_swigregister
Master_swigregister(Master)

def Master_Instance():
  return _xgui.Master_Instance()
Master_Instance = _xgui.Master_Instance

def Master_Quit():
  return _xgui.Master_Quit()
Master_Quit = _xgui.Master_Quit

def Master_RegisterIdleCallback(*args):
  return _xgui.Master_RegisterIdleCallback(*args)
Master_RegisterIdleCallback = _xgui.Master_RegisterIdleCallback

def Master_InitDynamicClasses():
  return _xgui.Master_InitDynamicClasses()
Master_InitDynamicClasses = _xgui.Master_InitDynamicClasses

def Master_CreateModel():
  return _xgui.Master_CreateModel()
Master_CreateModel = _xgui.Master_CreateModel

def Master_DestroyModel(*args):
  return _xgui.Master_DestroyModel(*args)
Master_DestroyModel = _xgui.Master_DestroyModel

def Master_CreateStyleManager():
  return _xgui.Master_CreateStyleManager()
Master_CreateStyleManager = _xgui.Master_CreateStyleManager

def Master_DestroyStyleManager(*args):
  return _xgui.Master_DestroyStyleManager(*args)
Master_DestroyStyleManager = _xgui.Master_DestroyStyleManager

def Master_LoadImage(*args):
  return _xgui.Master_LoadImage(*args)
Master_LoadImage = _xgui.Master_LoadImage

def Master_GetImage(*args):
  return _xgui.Master_GetImage(*args)
Master_GetImage = _xgui.Master_GetImage

def Master_NullImage():
  return _xgui.Master_NullImage()
Master_NullImage = _xgui.Master_NullImage

def Master_FindContext(*args):
  return _xgui.Master_FindContext(*args)
Master_FindContext = _xgui.Master_FindContext

def Master_CreateWindow(parent=None):
  return _xgui.Master_CreateWindow(parent)
Master_CreateWindow = _xgui.Master_CreateWindow

def Master_CreateButton(*args):
  return _xgui.Master_CreateButton(*args)
Master_CreateButton = _xgui.Master_CreateButton

def Master_CreateLabel(*args):
  return _xgui.Master_CreateLabel(*args)
Master_CreateLabel = _xgui.Master_CreateLabel

def Master_CreateEntry(*args):
  return _xgui.Master_CreateEntry(*args)
Master_CreateEntry = _xgui.Master_CreateEntry

def Master_CreateVBox(*args):
  return _xgui.Master_CreateVBox(*args)
Master_CreateVBox = _xgui.Master_CreateVBox

def Master_CreateHBox(*args):
  return _xgui.Master_CreateHBox(*args)
Master_CreateHBox = _xgui.Master_CreateHBox

def Master_CreateImageView(*args):
  return _xgui.Master_CreateImageView(*args)
Master_CreateImageView = _xgui.Master_CreateImageView

def Master_CreateList(*args):
  return _xgui.Master_CreateList(*args)
Master_CreateList = _xgui.Master_CreateList

def Master_CreateToolbar(*args):
  return _xgui.Master_CreateToolbar(*args)
Master_CreateToolbar = _xgui.Master_CreateToolbar

def Master_CreateCombobox(*args):
  return _xgui.Master_CreateCombobox(*args)
Master_CreateCombobox = _xgui.Master_CreateCombobox

def Master_CreateSpace(*args):
  return _xgui.Master_CreateSpace(*args)
Master_CreateSpace = _xgui.Master_CreateSpace

def Master_CreateCheckbox(*args):
  return _xgui.Master_CreateCheckbox(*args)
Master_CreateCheckbox = _xgui.Master_CreateCheckbox

def Master_CreateProgressbar(*args):
  return _xgui.Master_CreateProgressbar(*args)
Master_CreateProgressbar = _xgui.Master_CreateProgressbar

def Master_CreateSlider(*args):
  return _xgui.Master_CreateSlider(*args)
Master_CreateSlider = _xgui.Master_CreateSlider

def Master_CreateMenu(*args):
  return _xgui.Master_CreateMenu(*args)
Master_CreateMenu = _xgui.Master_CreateMenu

def Master_CreateTab(*args):
  return _xgui.Master_CreateTab(*args)
Master_CreateTab = _xgui.Master_CreateTab

def Master_CreateSpin(*args):
  return _xgui.Master_CreateSpin(*args)
Master_CreateSpin = _xgui.Master_CreateSpin

def Master_CreateFrame(*args):
  return _xgui.Master_CreateFrame(*args)
Master_CreateFrame = _xgui.Master_CreateFrame

def Master_CreateCalendar(*args):
  return _xgui.Master_CreateCalendar(*args)
Master_CreateCalendar = _xgui.Master_CreateCalendar

def Master_CreateTree(*args):
  return _xgui.Master_CreateTree(*args)
Master_CreateTree = _xgui.Master_CreateTree

def Master_LoadXml(*args):
  return _xgui.Master_LoadXml(*args)
Master_LoadXml = _xgui.Master_LoadXml

def Master_DestroyWidget(*args):
  return _xgui.Master_DestroyWidget(*args)
Master_DestroyWidget = _xgui.Master_DestroyWidget

def Master_InitThreads():
  return _xgui.Master_InitThreads()
Master_InitThreads = _xgui.Master_InitThreads

def Master_QuitThreads():
  return _xgui.Master_QuitThreads()
Master_QuitThreads = _xgui.Master_QuitThreads

def Master_GuiLock():
  return _xgui.Master_GuiLock()
Master_GuiLock = _xgui.Master_GuiLock

def Master_GuiUnlock():
  return _xgui.Master_GuiUnlock()
Master_GuiUnlock = _xgui.Master_GuiUnlock

def Master_Run():
  return _xgui.Master_Run()
Master_Run = _xgui.Master_Run

def Master_OpenFileDialog(*args):
  return _xgui.Master_OpenFileDialog(*args)
Master_OpenFileDialog = _xgui.Master_OpenFileDialog

def Master_SaveFileDialog(*args):
  return _xgui.Master_SaveFileDialog(*args)
Master_SaveFileDialog = _xgui.Master_SaveFileDialog

def Master_MessageDialog(*args):
  return _xgui.Master_MessageDialog(*args)
Master_MessageDialog = _xgui.Master_MessageDialog

class Callback(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Callback, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Callback, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def call(self, *args): return _xgui.Callback_call(self, *args)
    __swig_destroy__ = _xgui.delete_Callback
    __del__ = lambda self : None;
Callback_swigregister = _xgui.Callback_swigregister
Callback_swigregister(Callback)

class TextCallback(Callback):
    __swig_setmethods__ = {}
    for _s in [Callback]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TextCallback, name, value)
    __swig_getmethods__ = {}
    for _s in [Callback]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TextCallback, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def call(self, *args): return _xgui.TextCallback_call(self, *args)
    __swig_destroy__ = _xgui.delete_TextCallback
    __del__ = lambda self : None;
TextCallback_swigregister = _xgui.TextCallback_swigregister
TextCallback_swigregister(TextCallback)

class TextStatusCallback(Callback):
    __swig_setmethods__ = {}
    for _s in [Callback]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TextStatusCallback, name, value)
    __swig_getmethods__ = {}
    for _s in [Callback]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TextStatusCallback, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def call(self, *args): return _xgui.TextStatusCallback_call(self, *args)
    __swig_destroy__ = _xgui.delete_TextStatusCallback
    __del__ = lambda self : None;
TextStatusCallback_swigregister = _xgui.TextStatusCallback_swigregister
TextStatusCallback_swigregister(TextStatusCallback)

class TextPairCallback(Callback):
    __swig_setmethods__ = {}
    for _s in [Callback]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TextPairCallback, name, value)
    __swig_getmethods__ = {}
    for _s in [Callback]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TextPairCallback, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def call(self, *args): return _xgui.TextPairCallback_call(self, *args)
    __swig_destroy__ = _xgui.delete_TextPairCallback
    __del__ = lambda self : None;
TextPairCallback_swigregister = _xgui.TextPairCallback_swigregister
TextPairCallback_swigregister(TextPairCallback)

class PyCallback(Callback):
    __swig_setmethods__ = {}
    for _s in [Callback]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PyCallback, name, value)
    __swig_getmethods__ = {}
    for _s in [Callback]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, PyCallback, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _xgui.new_PyCallback(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _xgui.delete_PyCallback
    __del__ = lambda self : None;
    def call(self, *args): return _xgui.PyCallback_call(self, *args)
PyCallback_swigregister = _xgui.PyCallback_swigregister
PyCallback_swigregister(PyCallback)

class PyTextCallback(TextCallback):
    __swig_setmethods__ = {}
    for _s in [TextCallback]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PyTextCallback, name, value)
    __swig_getmethods__ = {}
    for _s in [TextCallback]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, PyTextCallback, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _xgui.new_PyTextCallback(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _xgui.delete_PyTextCallback
    __del__ = lambda self : None;
    def call(self, *args): return _xgui.PyTextCallback_call(self, *args)
PyTextCallback_swigregister = _xgui.PyTextCallback_swigregister
PyTextCallback_swigregister(PyTextCallback)

class PyTextStatusCallback(TextStatusCallback):
    __swig_setmethods__ = {}
    for _s in [TextStatusCallback]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PyTextStatusCallback, name, value)
    __swig_getmethods__ = {}
    for _s in [TextStatusCallback]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, PyTextStatusCallback, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _xgui.new_PyTextStatusCallback(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _xgui.delete_PyTextStatusCallback
    __del__ = lambda self : None;
    def call(self, *args): return _xgui.PyTextStatusCallback_call(self, *args)
PyTextStatusCallback_swigregister = _xgui.PyTextStatusCallback_swigregister
PyTextStatusCallback_swigregister(PyTextStatusCallback)

class PyTextPairCallback(TextPairCallback):
    __swig_setmethods__ = {}
    for _s in [TextPairCallback]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PyTextPairCallback, name, value)
    __swig_getmethods__ = {}
    for _s in [TextPairCallback]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, PyTextPairCallback, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _xgui.new_PyTextPairCallback(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _xgui.delete_PyTextPairCallback
    __del__ = lambda self : None;
    def call(self, *args): return _xgui.PyTextPairCallback_call(self, *args)
PyTextPairCallback_swigregister = _xgui.PyTextPairCallback_swigregister
PyTextPairCallback_swigregister(PyTextPairCallback)

# This file is compatible with both classic and new-style classes.


