# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _xgui
else:
    import _xgui

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _xgui.delete_SwigPyIterator

    def value(self):
        return _xgui.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _xgui.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _xgui.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _xgui.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _xgui.SwigPyIterator_equal(self, x)

    def copy(self):
        return _xgui.SwigPyIterator_copy(self)

    def next(self):
        return _xgui.SwigPyIterator_next(self)

    def __next__(self):
        return _xgui.SwigPyIterator___next__(self)

    def previous(self):
        return _xgui.SwigPyIterator_previous(self)

    def advance(self, n):
        return _xgui.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _xgui.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _xgui.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _xgui.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _xgui.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _xgui.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _xgui.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _xgui:
_xgui.SwigPyIterator_swigregister(SwigPyIterator)
keyShiftMask = _xgui.keyShiftMask
keyControlMask = _xgui.keyControlMask
keyAltMask = _xgui.keyAltMask
mouseLeftMask = _xgui.mouseLeftMask
mouseRightMask = _xgui.mouseRightMask
mouseMiddleMask = _xgui.mouseMiddleMask
PROPERTY_NOT_FOUND = _xgui.PROPERTY_NOT_FOUND
PROPERTY_READ_ONLY = _xgui.PROPERTY_READ_ONLY
PROPERTY_READ_WRITE = _xgui.PROPERTY_READ_WRITE
class FileExtension(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    name = property(_xgui.FileExtension_name_get, _xgui.FileExtension_name_set)
    extension = property(_xgui.FileExtension_extension_get, _xgui.FileExtension_extension_set)

    def __init__(self, *args):
        _xgui.FileExtension_swiginit(self, _xgui.new_FileExtension(*args))
    __swig_destroy__ = _xgui.delete_FileExtension

# Register FileExtension in _xgui:
_xgui.FileExtension_swigregister(FileExtension)
cvar = _xgui.cvar
EVT_BLOCK = cvar.EVT_BLOCK
EVT_PROPAGATE = cvar.EVT_PROPAGATE

class StringVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _xgui.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _xgui.StringVector___nonzero__(self)

    def __bool__(self):
        return _xgui.StringVector___bool__(self)

    def __len__(self):
        return _xgui.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _xgui.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _xgui.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _xgui.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _xgui.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _xgui.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _xgui.StringVector___setitem__(self, *args)

    def pop(self):
        return _xgui.StringVector_pop(self)

    def append(self, x):
        return _xgui.StringVector_append(self, x)

    def empty(self):
        return _xgui.StringVector_empty(self)

    def size(self):
        return _xgui.StringVector_size(self)

    def swap(self, v):
        return _xgui.StringVector_swap(self, v)

    def begin(self):
        return _xgui.StringVector_begin(self)

    def end(self):
        return _xgui.StringVector_end(self)

    def rbegin(self):
        return _xgui.StringVector_rbegin(self)

    def rend(self):
        return _xgui.StringVector_rend(self)

    def clear(self):
        return _xgui.StringVector_clear(self)

    def get_allocator(self):
        return _xgui.StringVector_get_allocator(self)

    def pop_back(self):
        return _xgui.StringVector_pop_back(self)

    def erase(self, *args):
        return _xgui.StringVector_erase(self, *args)

    def __init__(self, *args):
        _xgui.StringVector_swiginit(self, _xgui.new_StringVector(*args))

    def push_back(self, x):
        return _xgui.StringVector_push_back(self, x)

    def front(self):
        return _xgui.StringVector_front(self)

    def back(self):
        return _xgui.StringVector_back(self)

    def assign(self, n, x):
        return _xgui.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _xgui.StringVector_resize(self, *args)

    def insert(self, *args):
        return _xgui.StringVector_insert(self, *args)

    def reserve(self, n):
        return _xgui.StringVector_reserve(self, n)

    def capacity(self):
        return _xgui.StringVector_capacity(self)
    __swig_destroy__ = _xgui.delete_StringVector

# Register StringVector in _xgui:
_xgui.StringVector_swigregister(StringVector)
class FileExtensionsVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _xgui.FileExtensionsVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _xgui.FileExtensionsVector___nonzero__(self)

    def __bool__(self):
        return _xgui.FileExtensionsVector___bool__(self)

    def __len__(self):
        return _xgui.FileExtensionsVector___len__(self)

    def __getslice__(self, i, j):
        return _xgui.FileExtensionsVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _xgui.FileExtensionsVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _xgui.FileExtensionsVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _xgui.FileExtensionsVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _xgui.FileExtensionsVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _xgui.FileExtensionsVector___setitem__(self, *args)

    def pop(self):
        return _xgui.FileExtensionsVector_pop(self)

    def append(self, x):
        return _xgui.FileExtensionsVector_append(self, x)

    def empty(self):
        return _xgui.FileExtensionsVector_empty(self)

    def size(self):
        return _xgui.FileExtensionsVector_size(self)

    def swap(self, v):
        return _xgui.FileExtensionsVector_swap(self, v)

    def begin(self):
        return _xgui.FileExtensionsVector_begin(self)

    def end(self):
        return _xgui.FileExtensionsVector_end(self)

    def rbegin(self):
        return _xgui.FileExtensionsVector_rbegin(self)

    def rend(self):
        return _xgui.FileExtensionsVector_rend(self)

    def clear(self):
        return _xgui.FileExtensionsVector_clear(self)

    def get_allocator(self):
        return _xgui.FileExtensionsVector_get_allocator(self)

    def pop_back(self):
        return _xgui.FileExtensionsVector_pop_back(self)

    def erase(self, *args):
        return _xgui.FileExtensionsVector_erase(self, *args)

    def __init__(self, *args):
        _xgui.FileExtensionsVector_swiginit(self, _xgui.new_FileExtensionsVector(*args))

    def push_back(self, x):
        return _xgui.FileExtensionsVector_push_back(self, x)

    def front(self):
        return _xgui.FileExtensionsVector_front(self)

    def back(self):
        return _xgui.FileExtensionsVector_back(self)

    def assign(self, n, x):
        return _xgui.FileExtensionsVector_assign(self, n, x)

    def resize(self, *args):
        return _xgui.FileExtensionsVector_resize(self, *args)

    def insert(self, *args):
        return _xgui.FileExtensionsVector_insert(self, *args)

    def reserve(self, n):
        return _xgui.FileExtensionsVector_reserve(self, n)

    def capacity(self):
        return _xgui.FileExtensionsVector_capacity(self)
    __swig_destroy__ = _xgui.delete_FileExtensionsVector

# Register FileExtensionsVector in _xgui:
_xgui.FileExtensionsVector_swigregister(FileExtensionsVector)
class ClassInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _xgui.delete_ClassInfo

    def isInstanceable(self):
        return _xgui.ClassInfo_isInstanceable(self)

    def mustFinalize(self):
        return _xgui.ClassInfo_mustFinalize(self)

    def className(self):
        return _xgui.ClassInfo_className(self)

    def tag(self):
        return _xgui.ClassInfo_tag(self)

    def dtd(self):
        return _xgui.ClassInfo_dtd(self)

    def isContainer(self):
        return _xgui.ClassInfo_isContainer(self)

    def isWidget(self):
        return _xgui.ClassInfo_isWidget(self)

    def isModel(self):
        return _xgui.ClassInfo_isModel(self)

    def isStyleManager(self):
        return _xgui.ClassInfo_isStyleManager(self)

    def canContain(self, c):
        return _xgui.ClassInfo_canContain(self, c)

    def canBeContainedIn(self, c):
        return _xgui.ClassInfo_canBeContainedIn(self, c)

    def registerProperty(self, prop, setter, getter, dumpable):
        return _xgui.ClassInfo_registerProperty(self, prop, setter, getter, dumpable)

    def getPropertySetter(self, prop):
        return _xgui.ClassInfo_getPropertySetter(self, prop)

    def getPropertyGetter(self, prop):
        return _xgui.ClassInfo_getPropertyGetter(self, prop)

    def properties(self):
        return _xgui.ClassInfo_properties(self)

    def hasProperty(self, property):
        return _xgui.ClassInfo_hasProperty(self, property)

    def initProperties(self):
        return _xgui.ClassInfo_initProperties(self)

    def registerInitProperty(self, name, required):
        return _xgui.ClassInfo_registerInitProperty(self, name, required)

    def registerMethod(self, name, m):
        return _xgui.ClassInfo_registerMethod(self, name, m)

    def findMethod(self, name):
        return _xgui.ClassInfo_findMethod(self, name)

    def create(self, parent, properties):
        return _xgui.ClassInfo_create(self, parent, properties)

    def finalize(self, obj):
        return _xgui.ClassInfo_finalize(self, obj)

# Register ClassInfo in _xgui:
_xgui.ClassInfo_swigregister(ClassInfo)
class ObjectClass(ClassInfo):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.ObjectClass_swiginit(self, _xgui.new_ObjectClass())

    def create(self, parent, properties):
        return _xgui.ObjectClass_create(self, parent, properties)

    def finalize(self, arg2):
        return _xgui.ObjectClass_finalize(self, arg2)

    def canContain(self, c):
        return _xgui.ObjectClass_canContain(self, c)

    def canBeContainedIn(self, c):
        return _xgui.ObjectClass_canBeContainedIn(self, c)

    def isInstanceable(self):
        return _xgui.ObjectClass_isInstanceable(self)

    def mustFinalize(self):
        return _xgui.ObjectClass_mustFinalize(self)

    def className(self):
        return _xgui.ObjectClass_className(self)

    def isContainer(self):
        return _xgui.ObjectClass_isContainer(self)

    def isWidget(self):
        return _xgui.ObjectClass_isWidget(self)

    def isModel(self):
        return _xgui.ObjectClass_isModel(self)

    def isStyleManager(self):
        return _xgui.ObjectClass_isStyleManager(self)
    __swig_destroy__ = _xgui.delete_ObjectClass

# Register ObjectClass in _xgui:
_xgui.ObjectClass_swigregister(ObjectClass)
class Object(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def className(self):
        return _xgui.Object_className(self)

    def getClass(self):
        return _xgui.Object_getClass(self)

    def isIdentifiedAs(self, id):
        return _xgui.Object_isIdentifiedAs(self, id)

    def id(self):
        return _xgui.Object_id(self)

    def setId(self, id):
        return _xgui.Object_setId(self, id)

    def store(self, name, o, destroy=False):
        return _xgui.Object_store(self, name, o, destroy)

    def retrieve(self, name):
        return _xgui.Object_retrieve(self, name)

    def unstore(self, name):
        return _xgui.Object_unstore(self, name)

    def set(self, name, val):
        return _xgui.Object_set(self, name, val)

    def get(self, name):
        return _xgui.Object_get(self, name)

    def registerProperty(self, prop, setter, getter, dumpable):
        return _xgui.Object_registerProperty(self, prop, setter, getter, dumpable)

    def properties(self):
        return _xgui.Object_properties(self)

    def hasProperty(self, property):
        return _xgui.Object_hasProperty(self, property)

    @staticmethod
    def Unpack(obj):
        return _xgui.Object_Unpack(obj)

    def pack(self):
        return _xgui.Object_pack(self)

    def findMethod(self, name):
        return _xgui.Object_findMethod(self, name)

    def registerMethod(self, name, m):
        return _xgui.Object_registerMethod(self, name, m)

    def call(self, *args):
        return _xgui.Object_call(self, *args)

# Register Object in _xgui:
_xgui.Object_swigregister(Object)
class WidgetClass(ObjectClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.WidgetClass_swiginit(self, _xgui.new_WidgetClass())

    def isWidget(self):
        return _xgui.WidgetClass_isWidget(self)

    def className(self):
        return _xgui.WidgetClass_className(self)

    def canContain(self, c):
        return _xgui.WidgetClass_canContain(self, c)

    def canBeContainedIn(self, c):
        return _xgui.WidgetClass_canBeContainedIn(self, c)
    __swig_destroy__ = _xgui.delete_WidgetClass

# Register WidgetClass in _xgui:
_xgui.WidgetClass_swigregister(WidgetClass)
class Widget(Object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def getImpl(self):
        return _xgui.Widget_getImpl(self)

    def setAsFloating(self):
        return _xgui.Widget_setAsFloating(self)

    def getParent(self):
        return _xgui.Widget_getParent(self)

    def getContext(self):
        return _xgui.Widget_getContext(self)

    def getPath(self):
        return _xgui.Widget_getPath(self)

    def linkEvent(self, name, cb):
        return _xgui.Widget_linkEvent(self, name, cb)

    def getEvent(self, name):
        return _xgui.Widget_getEvent(self, name)

    def hasEvent(self, name):
        return _xgui.Widget_hasEvent(self, name)

    def recalcLayout(self):
        return _xgui.Widget_recalcLayout(self)

    def getMousePos(self):
        return _xgui.Widget_getMousePos(self)

    def redraw(self):
        return _xgui.Widget_redraw(self)

    def delPyOwner(self, pyobj):
        return _xgui.Widget_delPyOwner(self, pyobj)

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register Widget in _xgui:
_xgui.Widget_swigregister(Widget)
class ModelClass(ObjectClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.ModelClass_swiginit(self, _xgui.new_ModelClass())

    def className(self):
        return _xgui.ModelClass_className(self)

    def isInstanceable(self):
        return _xgui.ModelClass_isInstanceable(self)

    def isModel(self):
        return _xgui.ModelClass_isModel(self)

    def mustFinalize(self):
        return _xgui.ModelClass_mustFinalize(self)

    def create(self, parent, properties):
        return _xgui.ModelClass_create(self, parent, properties)

    def finalize(self, o):
        return _xgui.ModelClass_finalize(self, o)

    def canContain(self, c):
        return _xgui.ModelClass_canContain(self, c)

    def canBeContainedIn(self, c):
        return _xgui.ModelClass_canBeContainedIn(self, c)
    __swig_destroy__ = _xgui.delete_ModelClass

# Register ModelClass in _xgui:
_xgui.ModelClass_swigregister(ModelClass)
class Model(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def appendChild(self, *args):
        return _xgui.Model_appendChild(self, *args)

    def insertChild(self, child, pos):
        return _xgui.Model_insertChild(self, child, pos)

    def removeChild(self, pos):
        return _xgui.Model_removeChild(self, pos)

    def removeAllChildren(self):
        return _xgui.Model_removeAllChildren(self)

    def setChild(self, new_child, pos):
        return _xgui.Model_setChild(self, new_child, pos)

    def getChild(self, pos):
        return _xgui.Model_getChild(self, pos)

    def findByPath(self, path):
        return _xgui.Model_findByPath(self, path)

    def setFlag(self, flag):
        return _xgui.Model_setFlag(self, flag)

    def unsetFlag(self, flag):
        return _xgui.Model_unsetFlag(self, flag)

    def getFlagStatus(self, flag):
        return _xgui.Model_getFlagStatus(self, flag)

    def setStyle(self, style_name):
        return _xgui.Model_setStyle(self, style_name)

    def getStyle(self):
        return _xgui.Model_getStyle(self)

    def addString(self, str):
        return _xgui.Model_addString(self, str)

    def delString(self, pos):
        return _xgui.Model_delString(self, pos)

    def setString(self, str, pos):
        return _xgui.Model_setString(self, str, pos)

    def getString(self, pos):
        return _xgui.Model_getString(self, pos)

    def clearStrings(self):
        return _xgui.Model_clearStrings(self)

    def numberOfStrings(self):
        return _xgui.Model_numberOfStrings(self)

    def updateViews(self):
        return _xgui.Model_updateViews(self)

    def size(self):
        return _xgui.Model_size(self)

# Register Model in _xgui:
_xgui.Model_swigregister(Model)
class ContainerClass(WidgetClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.ContainerClass_swiginit(self, _xgui.new_ContainerClass())

    def className(self):
        return _xgui.ContainerClass_className(self)

    def isContainer(self):
        return _xgui.ContainerClass_isContainer(self)

    def canContain(self, c):
        return _xgui.ContainerClass_canContain(self, c)

    def canBeContainedIn(self, c):
        return _xgui.ContainerClass_canBeContainedIn(self, c)
    __swig_destroy__ = _xgui.delete_ContainerClass

# Register ContainerClass in _xgui:
_xgui.ContainerClass_swigregister(ContainerClass)
class Container(Widget):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def findChild(self, child_name):
        return _xgui.Container_findChild(self, child_name)

    def findDirectChild(self, child_name):
        return _xgui.Container_findDirectChild(self, child_name)

    def getChild(self, pos):
        return _xgui.Container_getChild(self, pos)

    def size(self):
        return _xgui.Container_size(self)

# Register Container in _xgui:
_xgui.Container_swigregister(Container)
class ViewClass(WidgetClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.ViewClass_swiginit(self, _xgui.new_ViewClass())

    def className(self):
        return _xgui.ViewClass_className(self)
    __swig_destroy__ = _xgui.delete_ViewClass

# Register ViewClass in _xgui:
_xgui.ViewClass_swigregister(ViewClass)
class View(Widget):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def setModel(self, model):
        return _xgui.View_setModel(self, model)

    def getModel(self):
        return _xgui.View_getModel(self)

    def refresh(self):
        return _xgui.View_refresh(self)

    def isSelected(self, parent, child_pos):
        return _xgui.View_isSelected(self, parent, child_pos)

    def select(self, parent, child_pos, state):
        return _xgui.View_select(self, parent, child_pos, state)

    def selectAll(self, parent, state):
        return _xgui.View_selectAll(self, parent, state)

# Register View in _xgui:
_xgui.View_swigregister(View)
class ImageClass(ObjectClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.ImageClass_swiginit(self, _xgui.new_ImageClass())

    def className(self):
        return _xgui.ImageClass_className(self)

    def isInstanceable(self):
        return _xgui.ImageClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.ImageClass_create(self, parent, properties)
    __swig_destroy__ = _xgui.delete_ImageClass

# Register ImageClass in _xgui:
_xgui.ImageClass_swigregister(ImageClass)
class Image(Object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def ref(self):
        return _xgui.Image_ref(self)

    def unref(self):
        return _xgui.Image_unref(self)

    def getPath(self):
        return _xgui.Image_getPath(self)

    def getWidth(self):
        return _xgui.Image_getWidth(self)

    def getHeight(self):
        return _xgui.Image_getHeight(self)

    def getImpl(self):
        return _xgui.Image_getImpl(self)

    def isValid(self):
        return _xgui.Image_isValid(self)

# Register Image in _xgui:
_xgui.Image_swigregister(Image)
class StyleManagerClass(ObjectClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.StyleManagerClass_swiginit(self, _xgui.new_StyleManagerClass())

    def className(self):
        return _xgui.StyleManagerClass_className(self)

    def isStyleManager(self):
        return _xgui.StyleManagerClass_isStyleManager(self)

    def isInstanceable(self):
        return _xgui.StyleManagerClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.StyleManagerClass_create(self, parent, properties)

    def canContain(self, c):
        return _xgui.StyleManagerClass_canContain(self, c)

    def canBeContainedIn(self, c):
        return _xgui.StyleManagerClass_canBeContainedIn(self, c)
    __swig_destroy__ = _xgui.delete_StyleManagerClass

# Register StyleManagerClass in _xgui:
_xgui.StyleManagerClass_swigregister(StyleManagerClass)
class StyleManager(Object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    TxtItalic = _xgui.StyleManager_TxtItalic
    TxtBold = _xgui.StyleManager_TxtBold
    TxtUnderline = _xgui.StyleManager_TxtUnderline
    TxtStrikeOut = _xgui.StyleManager_TxtStrikeOut

    def getImpl(self):
        return _xgui.StyleManager_getImpl(self)

    def ref(self):
        return _xgui.StyleManager_ref(self)

    def unref(self):
        return _xgui.StyleManager_unref(self)

    def addStyle(self, style_name, icon, fg_color, bg_color, text_style):
        return _xgui.StyleManager_addStyle(self, style_name, icon, fg_color, bg_color, text_style)

    def delStyle(self, style):
        return _xgui.StyleManager_delStyle(self, style)

    def isTextBold(self, style):
        return _xgui.StyleManager_isTextBold(self, style)

    def isTextItalic(self, style):
        return _xgui.StyleManager_isTextItalic(self, style)

    def isTextUnderlined(self, style):
        return _xgui.StyleManager_isTextUnderlined(self, style)

    def isTextStriked(self, style):
        return _xgui.StyleManager_isTextStriked(self, style)

    def getIcon(self, style):
        return _xgui.StyleManager_getIcon(self, style)

    def getFgColor(self, style):
        return _xgui.StyleManager_getFgColor(self, style)

    def getBgColor(self, style):
        return _xgui.StyleManager_getBgColor(self, style)

    def parseColorString(self, color):
        return _xgui.StyleManager_parseColorString(self, color)

    def dump(self):
        return _xgui.StyleManager_dump(self)

# Register StyleManager in _xgui:
_xgui.StyleManager_swigregister(StyleManager)
class ButtonClass(WidgetClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.ButtonClass_swiginit(self, _xgui.new_ButtonClass())

    def className(self):
        return _xgui.ButtonClass_className(self)

    def isInstanceable(self):
        return _xgui.ButtonClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.ButtonClass_create(self, parent, properties)
    __swig_destroy__ = _xgui.delete_ButtonClass

# Register ButtonClass in _xgui:
_xgui.ButtonClass_swigregister(ButtonClass)
class Button(Widget):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def setIcon(self, img):
        return _xgui.Button_setIcon(self, img)

    def getIcon(self):
        return _xgui.Button_getIcon(self)

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register Button in _xgui:
_xgui.Button_swigregister(Button)
class WindowClass(ContainerClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.WindowClass_swiginit(self, _xgui.new_WindowClass())

    def className(self):
        return _xgui.WindowClass_className(self)

    def isInstanceable(self):
        return _xgui.WindowClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.WindowClass_create(self, parent, properties)

    def canBeContainedIn(self, c):
        return _xgui.WindowClass_canBeContainedIn(self, c)
    __swig_destroy__ = _xgui.delete_WindowClass

# Register WindowClass in _xgui:
_xgui.WindowClass_swigregister(WindowClass)
class Window(Container):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def show(self):
        return _xgui.Window_show(self)

    def isModal(self):
        return _xgui.Window_isModal(self)

    def modalReturn(self, response):
        return _xgui.Window_modalReturn(self, response)

    def getRootChild(self):
        return _xgui.Window_getRootChild(self)

    def getMenu(self):
        return _xgui.Window_getMenu(self)

    def maximize(self):
        return _xgui.Window_maximize(self)

    def minimize(self):
        return _xgui.Window_minimize(self)

    def restore(self):
        return _xgui.Window_restore(self)

    def setIcon(self, img):
        return _xgui.Window_setIcon(self, img)

    def getIcon(self):
        return _xgui.Window_getIcon(self)

    def modalRun(self):
        return _xgui.Window_modalRun(self)

    def __del__(self):
            if self.valid: self.delPyOwner(self)


# Register Window in _xgui:
_xgui.Window_swigregister(Window)
class LabelClass(WidgetClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.LabelClass_swiginit(self, _xgui.new_LabelClass())

    def className(self):
        return _xgui.LabelClass_className(self)

    def isInstanceable(self):
        return _xgui.LabelClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.LabelClass_create(self, parent, properties)
    __swig_destroy__ = _xgui.delete_LabelClass

# Register LabelClass in _xgui:
_xgui.LabelClass_swigregister(LabelClass)
class Label(Widget):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register Label in _xgui:
_xgui.Label_swigregister(Label)
class HBoxClass(ContainerClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.HBoxClass_swiginit(self, _xgui.new_HBoxClass())

    def className(self):
        return _xgui.HBoxClass_className(self)

    def isInstanceable(self):
        return _xgui.HBoxClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.HBoxClass_create(self, parent, properties)

    def canContain(self, c):
        return _xgui.HBoxClass_canContain(self, c)
    __swig_destroy__ = _xgui.delete_HBoxClass

# Register HBoxClass in _xgui:
_xgui.HBoxClass_swigregister(HBoxClass)
class HBox(Container):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def setExpand(self, w, expand):
        return _xgui.HBox_setExpand(self, w, expand)

    def getExpand(self, w):
        return _xgui.HBox_getExpand(self, w)

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register HBox in _xgui:
_xgui.HBox_swigregister(HBox)
class VBoxClass(ContainerClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.VBoxClass_swiginit(self, _xgui.new_VBoxClass())

    def className(self):
        return _xgui.VBoxClass_className(self)

    def isInstanceable(self):
        return _xgui.VBoxClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.VBoxClass_create(self, parent, properties)

    def canContain(self, c):
        return _xgui.VBoxClass_canContain(self, c)
    __swig_destroy__ = _xgui.delete_VBoxClass

# Register VBoxClass in _xgui:
_xgui.VBoxClass_swigregister(VBoxClass)
class VBox(Container):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def setExpand(self, w, expand):
        return _xgui.VBox_setExpand(self, w, expand)

    def getExpand(self, w):
        return _xgui.VBox_getExpand(self, w)

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register VBox in _xgui:
_xgui.VBox_swigregister(VBox)
class EntryClass(WidgetClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.EntryClass_swiginit(self, _xgui.new_EntryClass())

    def className(self):
        return _xgui.EntryClass_className(self)

    def isInstanceable(self):
        return _xgui.EntryClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.EntryClass_create(self, parent, properties)
    __swig_destroy__ = _xgui.delete_EntryClass

# Register EntryClass in _xgui:
_xgui.EntryClass_swigregister(EntryClass)
class Entry(Widget):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def appendText(self, text):
        return _xgui.Entry_appendText(self, text)

    def prependText(self, text):
        return _xgui.Entry_prependText(self, text)

    def insertText(self, text, pos):
        return _xgui.Entry_insertText(self, text, pos)

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register Entry in _xgui:
_xgui.Entry_swigregister(Entry)
class ListClass(ViewClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.ListClass_swiginit(self, _xgui.new_ListClass())

    def isInstanceable(self):
        return _xgui.ListClass_isInstanceable(self)

    def className(self):
        return _xgui.ListClass_className(self)

    def create(self, parent, properties):
        return _xgui.ListClass_create(self, parent, properties)

    def canContain(self, c):
        return _xgui.ListClass_canContain(self, c)
    __swig_destroy__ = _xgui.delete_ListClass

# Register ListClass in _xgui:
_xgui.ListClass_swigregister(ListClass)
class List(View):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def addColumn(self, *args):
        return _xgui.List_addColumn(self, *args)

    def delColumn(self, id):
        return _xgui.List_delColumn(self, id)

    def sort(self, column_id, callback):
        return _xgui.List_sort(self, column_id, callback)

    def isChecked(self, parent, child_pos):
        return _xgui.List_isChecked(self, parent, child_pos)

    def check(self, parent, child_pos, state):
        return _xgui.List_check(self, parent, child_pos, state)

    def checkAll(self, parent, state):
        return _xgui.List_checkAll(self, parent, state)

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register List in _xgui:
_xgui.List_swigregister(List)
class TreeClass(ViewClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.TreeClass_swiginit(self, _xgui.new_TreeClass())

    def className(self):
        return _xgui.TreeClass_className(self)

    def isInstanceable(self):
        return _xgui.TreeClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.TreeClass_create(self, parent, properties)

    def canContain(self, c):
        return _xgui.TreeClass_canContain(self, c)
    __swig_destroy__ = _xgui.delete_TreeClass

# Register TreeClass in _xgui:
_xgui.TreeClass_swigregister(TreeClass)
class Tree(View):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def sort(self, node, callback):
        return _xgui.Tree_sort(self, node, callback)

    def expand(self, node):
        return _xgui.Tree_expand(self, node)

    def collapse(self, node):
        return _xgui.Tree_collapse(self, node)

    def isChecked(self, parent, child_pos):
        return _xgui.Tree_isChecked(self, parent, child_pos)

    def check(self, parent, child_pos, state):
        return _xgui.Tree_check(self, parent, child_pos, state)

    def checkAll(self, parent, state):
        return _xgui.Tree_checkAll(self, parent, state)

# Register Tree in _xgui:
_xgui.Tree_swigregister(Tree)
class ToolbarClass(WidgetClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.ToolbarClass_swiginit(self, _xgui.new_ToolbarClass())

    def className(self):
        return _xgui.ToolbarClass_className(self)

    def isInstanceable(self):
        return _xgui.ToolbarClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.ToolbarClass_create(self, parent, properties)

    def canContain(self, c):
        return _xgui.ToolbarClass_canContain(self, c)
    __swig_destroy__ = _xgui.delete_ToolbarClass

# Register ToolbarClass in _xgui:
_xgui.ToolbarClass_swigregister(ToolbarClass)
class Toolbar(Widget):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def addItem(self, *args):
        return _xgui.Toolbar_addItem(self, *args)

    def delItem(self, name):
        return _xgui.Toolbar_delItem(self, name)

    def enableButton(self, name):
        return _xgui.Toolbar_enableButton(self, name)

    def disableButton(self, name):
        return _xgui.Toolbar_disableButton(self, name)

    def checkButton(self, name):
        return _xgui.Toolbar_checkButton(self, name)

    def uncheckButton(self, name):
        return _xgui.Toolbar_uncheckButton(self, name)

    def isButtonChecked(self, name):
        return _xgui.Toolbar_isButtonChecked(self, name)

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register Toolbar in _xgui:
_xgui.Toolbar_swigregister(Toolbar)
class ComboboxClass(ViewClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.ComboboxClass_swiginit(self, _xgui.new_ComboboxClass())

    def isInstanceable(self):
        return _xgui.ComboboxClass_isInstanceable(self)

    def className(self):
        return _xgui.ComboboxClass_className(self)

    def create(self, parent, properties):
        return _xgui.ComboboxClass_create(self, parent, properties)

    def canContain(self, c):
        return _xgui.ComboboxClass_canContain(self, c)
    __swig_destroy__ = _xgui.delete_ComboboxClass

# Register ComboboxClass in _xgui:
_xgui.ComboboxClass_swigregister(ComboboxClass)
class Combobox(View):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def insertText(self, text, pos):
        return _xgui.Combobox_insertText(self, text, pos)

    def appendText(self, text):
        return _xgui.Combobox_appendText(self, text)

    def prependText(self, text):
        return _xgui.Combobox_prependText(self, text)

    def popup(self):
        return _xgui.Combobox_popup(self)

    def popdown(self):
        return _xgui.Combobox_popdown(self)

    def isEditable(self):
        return _xgui.Combobox_isEditable(self)

    def setAsEditable(self, editable):
        return _xgui.Combobox_setAsEditable(self, editable)

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register Combobox in _xgui:
_xgui.Combobox_swigregister(Combobox)
class SpaceClass(WidgetClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.SpaceClass_swiginit(self, _xgui.new_SpaceClass())

    def className(self):
        return _xgui.SpaceClass_className(self)

    def isInstanceable(self):
        return _xgui.SpaceClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.SpaceClass_create(self, parent, properties)
    __swig_destroy__ = _xgui.delete_SpaceClass

# Register SpaceClass in _xgui:
_xgui.SpaceClass_swigregister(SpaceClass)
class Space(Widget):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register Space in _xgui:
_xgui.Space_swigregister(Space)
class CheckboxClass(WidgetClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.CheckboxClass_swiginit(self, _xgui.new_CheckboxClass())

    def className(self):
        return _xgui.CheckboxClass_className(self)

    def isInstanceable(self):
        return _xgui.CheckboxClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.CheckboxClass_create(self, parent, properties)
    __swig_destroy__ = _xgui.delete_CheckboxClass

# Register CheckboxClass in _xgui:
_xgui.CheckboxClass_swigregister(CheckboxClass)
class Checkbox(Widget):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def getValue(self):
        return _xgui.Checkbox_getValue(self)

    def setValue(self, arg2):
        return _xgui.Checkbox_setValue(self, arg2)

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register Checkbox in _xgui:
_xgui.Checkbox_swigregister(Checkbox)
class ProgressbarClass(WidgetClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.ProgressbarClass_swiginit(self, _xgui.new_ProgressbarClass())

    def className(self):
        return _xgui.ProgressbarClass_className(self)

    def isInstanceable(self):
        return _xgui.ProgressbarClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.ProgressbarClass_create(self, parent, properties)
    __swig_destroy__ = _xgui.delete_ProgressbarClass

# Register ProgressbarClass in _xgui:
_xgui.ProgressbarClass_swigregister(ProgressbarClass)
class Progressbar(Widget):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def getPos(self):
        return _xgui.Progressbar_getPos(self)

    def setPos(self, pos):
        return _xgui.Progressbar_setPos(self, pos)

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register Progressbar in _xgui:
_xgui.Progressbar_swigregister(Progressbar)
class SliderClass(WidgetClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.SliderClass_swiginit(self, _xgui.new_SliderClass())

    def className(self):
        return _xgui.SliderClass_className(self)

    def isInstanceable(self):
        return _xgui.SliderClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.SliderClass_create(self, parent, properties)
    __swig_destroy__ = _xgui.delete_SliderClass

# Register SliderClass in _xgui:
_xgui.SliderClass_swigregister(SliderClass)
class Slider(Widget):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def getPos(self):
        return _xgui.Slider_getPos(self)

    def setPos(self, pos):
        return _xgui.Slider_setPos(self, pos)

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register Slider in _xgui:
_xgui.Slider_swigregister(Slider)
class MenuClass(WidgetClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.MenuClass_swiginit(self, _xgui.new_MenuClass())

    def className(self):
        return _xgui.MenuClass_className(self)

    def isInstanceable(self):
        return _xgui.MenuClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.MenuClass_create(self, parent, properties)

    def canContain(self, c):
        return _xgui.MenuClass_canContain(self, c)

    def canBeContainedIn(self, c):
        return _xgui.MenuClass_canBeContainedIn(self, c)
    __swig_destroy__ = _xgui.delete_MenuClass

# Register MenuClass in _xgui:
_xgui.MenuClass_swigregister(MenuClass)
class Menu(Widget):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def addItem(self, *args):
        return _xgui.Menu_addItem(self, *args)

    def delItem(self, id):
        return _xgui.Menu_delItem(self, id)

    def popupMenu(self, id):
        return _xgui.Menu_popupMenu(self, id)

    def enableItem(self, id):
        return _xgui.Menu_enableItem(self, id)

    def disableItem(self, id):
        return _xgui.Menu_disableItem(self, id)

    def isItemEnabled(self, id):
        return _xgui.Menu_isItemEnabled(self, id)

    def checkItem(self, id):
        return _xgui.Menu_checkItem(self, id)

    def uncheckItem(self, id):
        return _xgui.Menu_uncheckItem(self, id)

    def isItemChecked(self, id):
        return _xgui.Menu_isItemChecked(self, id)

    def setItemText(self, id, text):
        return _xgui.Menu_setItemText(self, id, text)

    def getItemText(self, id):
        return _xgui.Menu_getItemText(self, id)

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register Menu in _xgui:
_xgui.Menu_swigregister(Menu)
class TabClass(ContainerClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.TabClass_swiginit(self, _xgui.new_TabClass())

    def className(self):
        return _xgui.TabClass_className(self)

    def isInstanceable(self):
        return _xgui.TabClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.TabClass_create(self, parent, properties)

    def canContain(self, c):
        return _xgui.TabClass_canContain(self, c)
    __swig_destroy__ = _xgui.delete_TabClass

# Register TabClass in _xgui:
_xgui.TabClass_swigregister(TabClass)
class Tab(Container):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def setPageIcon(self, arg2, icon):
        return _xgui.Tab_setPageIcon(self, arg2, icon)

    def setPageLabel(self, arg2, str):
        return _xgui.Tab_setPageLabel(self, arg2, str)

    def getPageIcon(self, w):
        return _xgui.Tab_getPageIcon(self, w)

    def getPageLabel(self, w):
        return _xgui.Tab_getPageLabel(self, w)

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register Tab in _xgui:
_xgui.Tab_swigregister(Tab)
class SpinClass(WidgetClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.SpinClass_swiginit(self, _xgui.new_SpinClass())

    def className(self):
        return _xgui.SpinClass_className(self)

    def isInstanceable(self):
        return _xgui.SpinClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.SpinClass_create(self, parent, properties)
    __swig_destroy__ = _xgui.delete_SpinClass

# Register SpinClass in _xgui:
_xgui.SpinClass_swigregister(SpinClass)
class Spin(Widget):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register Spin in _xgui:
_xgui.Spin_swigregister(Spin)
class ImageViewClass(WidgetClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.ImageViewClass_swiginit(self, _xgui.new_ImageViewClass())

    def className(self):
        return _xgui.ImageViewClass_className(self)

    def isInstanceable(self):
        return _xgui.ImageViewClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.ImageViewClass_create(self, parent, properties)
    __swig_destroy__ = _xgui.delete_ImageViewClass

# Register ImageViewClass in _xgui:
_xgui.ImageViewClass_swigregister(ImageViewClass)
class ImageView(Widget):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def getImage(self):
        return _xgui.ImageView_getImage(self)

    def setImage(self, img):
        return _xgui.ImageView_setImage(self, img)

    def getViewSize(self):
        return _xgui.ImageView_getViewSize(self)

    def isScrolled(self):
        return _xgui.ImageView_isScrolled(self)

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register ImageView in _xgui:
_xgui.ImageView_swigregister(ImageView)
class FrameClass(ContainerClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.FrameClass_swiginit(self, _xgui.new_FrameClass())

    def className(self):
        return _xgui.FrameClass_className(self)

    def isInstanceable(self):
        return _xgui.FrameClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.FrameClass_create(self, parent, properties)
    __swig_destroy__ = _xgui.delete_FrameClass

# Register FrameClass in _xgui:
_xgui.FrameClass_swigregister(FrameClass)
class Frame(Container):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def getRootChild(self):
        return _xgui.Frame_getRootChild(self)

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register Frame in _xgui:
_xgui.Frame_swigregister(Frame)
class CalendarClass(WidgetClass):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _xgui.CalendarClass_swiginit(self, _xgui.new_CalendarClass())

    def className(self):
        return _xgui.CalendarClass_className(self)

    def isInstanceable(self):
        return _xgui.CalendarClass_isInstanceable(self)

    def create(self, parent, properties):
        return _xgui.CalendarClass_create(self, parent, properties)
    __swig_destroy__ = _xgui.delete_CalendarClass

# Register CalendarClass in _xgui:
_xgui.CalendarClass_swigregister(CalendarClass)
class Calendar(Widget):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __del__(self):
    	if self.valid: self.delPyOwner(self)


# Register Calendar in _xgui:
_xgui.Calendar_swigregister(Calendar)
class Master(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def Instance():
        return _xgui.Master_Instance()

    @staticmethod
    def Quit():
        return _xgui.Master_Quit()

    @staticmethod
    def RegisterIdleCallback(cbk, wid):
        return _xgui.Master_RegisterIdleCallback(cbk, wid)

    @staticmethod
    def InitDynamicClasses():
        return _xgui.Master_InitDynamicClasses()

    @staticmethod
    def CreateModel():
        return _xgui.Master_CreateModel()

    @staticmethod
    def DestroyModel(model):
        return _xgui.Master_DestroyModel(model)

    @staticmethod
    def CreateStyleManager():
        return _xgui.Master_CreateStyleManager()

    @staticmethod
    def DestroyStyleManager(sm):
        return _xgui.Master_DestroyStyleManager(sm)

    @staticmethod
    def LoadImage(path):
        return _xgui.Master_LoadImage(path)

    @staticmethod
    def GetImage(path):
        return _xgui.Master_GetImage(path)

    @staticmethod
    def NullImage():
        return _xgui.Master_NullImage()

    @staticmethod
    def FindContext(cname):
        return _xgui.Master_FindContext(cname)

    @staticmethod
    def CreateWindow(parent=None):
        return _xgui.Master_CreateWindow(parent)

    @staticmethod
    def CreateButton(parent, text, image=None, toggle_button=False):
        return _xgui.Master_CreateButton(parent, text, image, toggle_button)

    @staticmethod
    def CreateLabel(parent, text):
        return _xgui.Master_CreateLabel(parent, text)

    @staticmethod
    def CreateEntry(parent, text, maxlen=0, editable=True, password_mode=False):
        return _xgui.Master_CreateEntry(parent, text, maxlen, editable, password_mode)

    @staticmethod
    def CreateVBox(parent, space=0, border=False):
        return _xgui.Master_CreateVBox(parent, space, border)

    @staticmethod
    def CreateHBox(parent, space=0, border=False):
        return _xgui.Master_CreateHBox(parent, space, border)

    @staticmethod
    def CreateImageView(parent, img=None):
        return _xgui.Master_CreateImageView(parent, img)

    @staticmethod
    def CreateList(parent):
        return _xgui.Master_CreateList(parent)

    @staticmethod
    def CreateToolbar(parent):
        return _xgui.Master_CreateToolbar(parent)

    @staticmethod
    def CreateCombobox(parent, editable=False):
        return _xgui.Master_CreateCombobox(parent, editable)

    @staticmethod
    def CreateSpace(parent, width=1, height=1):
        return _xgui.Master_CreateSpace(parent, width, height)

    @staticmethod
    def CreateCheckbox(parent, text):
        return _xgui.Master_CreateCheckbox(parent, text)

    @staticmethod
    def CreateProgressbar(parent, min=0, max=100):
        return _xgui.Master_CreateProgressbar(parent, min, max)

    @staticmethod
    def CreateSlider(parent, min=0, max=100, vertical=False):
        return _xgui.Master_CreateSlider(parent, min, max, vertical)

    @staticmethod
    def CreateMenu(parent, visible=True):
        return _xgui.Master_CreateMenu(parent, visible)

    @staticmethod
    def CreateTab(*args):
        return _xgui.Master_CreateTab(*args)

    @staticmethod
    def CreateSpin(parent, min=0, max=100):
        return _xgui.Master_CreateSpin(parent, min, max)

    @staticmethod
    def CreateFrame(parent, label):
        return _xgui.Master_CreateFrame(parent, label)

    @staticmethod
    def CreateCalendar(parent):
        return _xgui.Master_CreateCalendar(parent)

    @staticmethod
    def CreateTree(parent):
        return _xgui.Master_CreateTree(parent)

    @staticmethod
    def LoadXml(file_name):
        return _xgui.Master_LoadXml(file_name)

    @staticmethod
    def LoadJson(file_name):
        return _xgui.Master_LoadJson(file_name)

    @staticmethod
    def DestroyWidget(w):
        return _xgui.Master_DestroyWidget(w)

    @staticmethod
    def InitThreads():
        return _xgui.Master_InitThreads()

    @staticmethod
    def QuitThreads():
        return _xgui.Master_QuitThreads()

    @staticmethod
    def GuiLock():
        return _xgui.Master_GuiLock()

    @staticmethod
    def GuiUnlock():
        return _xgui.Master_GuiUnlock()

    @staticmethod
    def Run():
        return _xgui.Master_Run()

    @staticmethod
    def OpenFileDialog(*args):
        return _xgui.Master_OpenFileDialog(*args)

    @staticmethod
    def SaveFileDialog(*args):
        return _xgui.Master_SaveFileDialog(*args)

    @staticmethod
    def MessageDialog(*args):
        return _xgui.Master_MessageDialog(*args)

# Register Master in _xgui:
_xgui.Master_swigregister(Master)
class Callback(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def call(self, arg2):
        return _xgui.Callback_call(self, arg2)
    __swig_destroy__ = _xgui.delete_Callback

# Register Callback in _xgui:
_xgui.Callback_swigregister(Callback)
class TextCallback(Callback):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def call(self, arg2, text):
        return _xgui.TextCallback_call(self, arg2, text)
    __swig_destroy__ = _xgui.delete_TextCallback

# Register TextCallback in _xgui:
_xgui.TextCallback_swigregister(TextCallback)
class TextStatusCallback(Callback):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def call(self, arg2, text, state):
        return _xgui.TextStatusCallback_call(self, arg2, text, state)
    __swig_destroy__ = _xgui.delete_TextStatusCallback

# Register TextStatusCallback in _xgui:
_xgui.TextStatusCallback_swigregister(TextStatusCallback)
class TextPairCallback(Callback):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def call(self, arg2, text1, text2):
        return _xgui.TextPairCallback_call(self, arg2, text1, text2)
    __swig_destroy__ = _xgui.delete_TextPairCallback

# Register TextPairCallback in _xgui:
_xgui.TextPairCallback_swigregister(TextPairCallback)
class PyCallback(Callback):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, cb):
        _xgui.PyCallback_swiginit(self, _xgui.new_PyCallback(cb))
    __swig_destroy__ = _xgui.delete_PyCallback

    def call(self, w):
        return _xgui.PyCallback_call(self, w)

# Register PyCallback in _xgui:
_xgui.PyCallback_swigregister(PyCallback)
class PyTextCallback(TextCallback):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, cb):
        _xgui.PyTextCallback_swiginit(self, _xgui.new_PyTextCallback(cb))
    __swig_destroy__ = _xgui.delete_PyTextCallback

    def call(self, w, str):
        return _xgui.PyTextCallback_call(self, w, str)

# Register PyTextCallback in _xgui:
_xgui.PyTextCallback_swigregister(PyTextCallback)
class PyTextStatusCallback(TextStatusCallback):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, cb):
        _xgui.PyTextStatusCallback_swiginit(self, _xgui.new_PyTextStatusCallback(cb))
    __swig_destroy__ = _xgui.delete_PyTextStatusCallback

    def call(self, w, str, status):
        return _xgui.PyTextStatusCallback_call(self, w, str, status)

# Register PyTextStatusCallback in _xgui:
_xgui.PyTextStatusCallback_swigregister(PyTextStatusCallback)
class PyTextPairCallback(TextPairCallback):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, cb):
        _xgui.PyTextPairCallback_swiginit(self, _xgui.new_PyTextPairCallback(cb))
    __swig_destroy__ = _xgui.delete_PyTextPairCallback

    def call(self, w, str, str2):
        return _xgui.PyTextPairCallback_call(self, w, str, str2)

# Register PyTextPairCallback in _xgui:
_xgui.PyTextPairCallback_swigregister(PyTextPairCallback)

